#!/usr/bin/env python3
"""Build CEFR-banded MSA vocab, ar→en gloss, and a root-meaning lexicon.

Pedagogical bands always win. Lemmas are stored undiacritized so they match
CAMeL output after `normalize_lemma`.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

_DIAC = re.compile(r"[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED]")


def _norm(text: str) -> str:
    s = _DIAC.sub("", text.replace("ـ", "")).strip()
    return s.translate(str.maketrans({"أ": "ا", "إ": "ا", "آ": "ا", "ٱ": "ا", "ى": "ي"}))

ROOT = Path(__file__).resolve().parents[1]
VOCAB_OUT = ROOT / "data" / "vocab" / "ar_cefr.json"
GLOSS_OUT = ROOT / "data" / "gloss" / "ar_en.json"
ROOTS_OUT = ROOT / "data" / "roots" / "ar.json"

PEDAGOGICAL: dict[str, tuple[str, str]] = {}
ROOTS: dict[str, str] = {}


def add(level: str, pairs: list[tuple[str, str]]) -> None:
    for lemma, gloss in pairs:
        lemma = _norm(lemma)
        if lemma and lemma not in PEDAGOGICAL:
            PEDAGOGICAL[lemma] = (level, gloss.strip())


def root(letters: str, meaning: str) -> None:
    key = _norm(letters.replace(" ", ""))
    if key and key not in ROOTS:
        ROOTS[key] = meaning.strip()


add(
    "A1",
    [
        ("انا", "I"),
        ("أنا", "I"),
        ("انت", "you (masc)"),
        ("أنت", "you (masc)"),
        ("انت", "you"),
        ("انتي", "you (fem)"),
        ("أنتِ", "you (fem)"),
        ("هو", "he"),
        ("هي", "she"),
        ("نحن", "we"),
        ("انتم", "you (pl masc)"),
        ("أنتم", "you (pl masc)"),
        ("انتن", "you (pl fem)"),
        ("هم", "they (masc)"),
        ("هن", "they (fem)"),
        ("هذا", "this (masc)"),
        ("هذه", "this (fem)"),
        ("ذلك", "that (masc)"),
        ("تلك", "that (fem)"),
        ("هنا", "here"),
        ("هناك", "there"),
        ("من", "from / who"),
        ("الى", "to"),
        ("إلى", "to"),
        ("في", "in"),
        ("على", "on"),
        ("عن", "about"),
        ("مع", "with"),
        ("و", "and"),
        ("او", "or"),
        ("أو", "or"),
        ("لا", "no / not"),
        ("ما", "what / not"),
        ("هل", "yes/no question"),
        ("نعم", "yes"),
        ("ليس", "is not"),
        ("كل", "every / all"),
        ("بعض", "some"),
        ("ايضا", "also"),
        ("أيضا", "also"),
        ("جدا", "very"),
        ("اليوم", "today"),
        ("الان", "now"),
        ("الآن", "now"),
        ("غدا", "tomorrow"),
        ("امس", "yesterday"),
        ("أمس", "yesterday"),
        ("صباح", "morning"),
        ("مساء", "evening"),
        ("ليل", "night"),
        ("يوم", "day"),
        ("اسبوع", "week"),
        ("أسبوع", "week"),
        ("شهر", "month"),
        ("سنة", "year"),
        ("وقت", "time"),
        ("ساعة", "hour / watch"),
        ("بيت", "house"),
        ("منزل", "home"),
        ("غرفة", "room"),
        ("باب", "door"),
        ("نافذة", "window"),
        ("طاولة", "table"),
        ("كرسي", "chair"),
        ("سرير", "bed"),
        ("مطبخ", "kitchen"),
        ("حمام", "bathroom"),
        ("ماء", "water"),
        ("شاي", "tea"),
        ("قهوة", "coffee"),
        ("خبز", "bread"),
        ("طعام", "food"),
        ("اكل", "food / eating"),
        ("أكل", "food / eating"),
        ("فاكهة", "fruit"),
        ("تفاح", "apple"),
        ("تفاحة", "apple"),
        ("حليب", "milk"),
        ("سكر", "sugar"),
        ("ملح", "salt"),
        ("لحم", "meat"),
        ("سمك", "fish"),
        ("رز", "rice"),
        ("كتاب", "book"),
        ("قلم", "pen"),
        ("ورقة", "paper / sheet"),
        ("مدرسة", "school"),
        ("طالب", "student (masc)"),
        ("طالبة", "student (fem)"),
        ("معلم", "teacher (masc)"),
        ("معلمة", "teacher (fem)"),
        ("درس", "lesson"),
        ("لغة", "language"),
        ("عربي", "Arabic"),
        ("عربية", "Arabic (fem)"),
        ("انكليزي", "English"),
        ("إنجليزي", "English"),
        ("اسم", "name"),
        ("ولد", "boy"),
        ("بنت", "girl"),
        ("رجل", "man"),
        ("امرأة", "woman"),
        ("امراة", "woman"),
        ("طفل", "child"),
        ("ام", "mother"),
        ("أم", "mother"),
        ("اب", "father"),
        ("أب", "father"),
        ("اخ", "brother"),
        ("أخ", "brother"),
        ("اخت", "sister"),
        ("أخت", "sister"),
        ("ابن", "son"),
        ("ابنة", "daughter"),
        ("عائلة", "family"),
        ("صديق", "friend (masc)"),
        ("صديقة", "friend (fem)"),
        ("ناس", "people"),
        ("شخص", "person"),
        ("مدينة", "city"),
        ("قرية", "village"),
        ("شارع", "street"),
        ("سوق", "market"),
        ("محل", "shop"),
        ("متجر", "store"),
        ("مطعم", "restaurant"),
        ("فندق", "hotel"),
        ("محطة", "station"),
        ("قطار", "train"),
        ("سيارة", "car"),
        ("حافلة", "bus"),
        ("طائرة", "airplane"),
        ("مطار", "airport"),
        ("بيت", "house"),
        ("عمل", "work"),
        ("وظيفة", "job"),
        ("مكتب", "office / desk"),
        ("طبيب", "doctor"),
        ("مستشفى", "hospital"),
        ("صيدلية", "pharmacy"),
        ("مال", "money"),
        ("سعر", "price"),
        ("رقم", "number"),
        ("واحد", "one"),
        ("اثنان", "two"),
        ("اثنين", "two"),
        ("ثلاثة", "three"),
        ("اربعة", "four"),
        ("أربعة", "four"),
        ("خمسة", "five"),
        ("ستة", "six"),
        ("سبعة", "seven"),
        ("ثمانية", "eight"),
        ("تسعة", "nine"),
        ("عشرة", "ten"),
        ("اول", "first"),
        ("أول", "first"),
        ("كبير", "big"),
        ("صغير", "small"),
        ("جديد", "new"),
        ("قديم", "old (thing)"),
        ("طويل", "tall / long"),
        ("قصير", "short"),
        ("جيد", "good"),
        ("سيء", "bad"),
        ("سيئ", "bad"),
        ("جميل", "beautiful"),
        ("سهل", "easy"),
        ("صعب", "difficult"),
        ("حار", "hot"),
        ("بارد", "cold"),
        ("قريب", "near"),
        ("بعيد", "far"),
        ("كثير", "many / much"),
        ("قليل", "few / little"),
        ("مفتوح", "open"),
        ("مغلق", "closed"),
        ("سعيد", "happy"),
        ("حزين", "sad"),
        ("مريض", "sick"),
        ("لون", "color"),
        ("ابيض", "white"),
        ("أبيض", "white"),
        ("اسود", "black"),
        ("أسود", "black"),
        ("احمر", "red"),
        ("أحمر", "red"),
        ("ازرق", "blue"),
        ("أزرق", "blue"),
        ("اخضر", "green"),
        ("أخضر", "green"),
        ("اصفر", "yellow"),
        ("أصفر", "yellow"),
        ("ذهب", "to go"),
        ("يذهب", "he goes"),
        ("اكل", "to eat"),
        ("أكل", "to eat"),
        ("شرب", "to drink"),
        ("كتب", "to write"),
        ("قرا", "to read"),
        ("قرأ", "to read"),
        ("سكن", "to live (in a place)"),
        ("عمل", "to work"),
        ("درس", "to study"),
        ("فهم", "to understand"),
        ("عرف", "to know"),
        ("قال", "to say"),
        ("سمع", "to hear"),
        ("راى", "to see"),
        ("رأى", "to see"),
        ("جاء", "to come"),
        ("فتح", "to open"),
        ("دخل", "to enter"),
        ("خرج", "to exit"),
        ("جلس", "to sit"),
        ("وقف", "to stand"),
        ("نام", "to sleep"),
        ("قام", "to get up"),
        ("اخذ", "to take"),
        ("أخذ", "to take"),
        ("وضع", "to put"),
        ("وجد", "to find"),
        ("اراد", "to want"),
        ("أراد", "to want"),
        ("قدر", "to be able"),
        ("حب", "to love"),
        ("احب", "to love"),
        ("أحب", "to love"),
        ("لعب", "to play"),
        ("اشترى", "to buy"),
        ("اشتر", "to buy"),
        ("باع", "to sell"),
        ("كان", "to be (was)"),
        ("يكون", "to be"),
        ("يوجد", "there is"),
        ("شكرا", "thank you"),
        ("عفوا", "you're welcome / excuse me"),
        ("من فضلك", "please"),
        ("سلام", "peace / hello"),
        ("مرحبا", "hello"),
        ("اهلا", "welcome"),
        ("أهلا", "welcome"),
        ("صباح الخير", "good morning"),
        ("مساء الخير", "good evening"),
        ("كيف", "how"),
        ("اين", "where"),
        ("أين", "where"),
        ("متى", "when"),
        ("ماذا", "what"),
        ("لماذا", "why"),
        ("كم", "how many"),
        ("بعد", "after"),
        ("قبل", "before"),
        ("تحت", "under"),
        ("فوق", "above"),
        ("امام", "in front of"),
        ("أمام", "in front of"),
        ("وراء", "behind"),
        ("بين", "between"),
        ("عند", "at / have"),
        ("لدى", "have / at"),
        ("لكن", "but"),
        ("ثم", "then"),
        ("اي", "any / which"),
        ("أي", "any / which"),
        ("شيء", "thing"),
        ("شي", "thing"),
    ],
)

add(
    "A2",
    [
        ("امس", "yesterday"),
        ("أسبوع", "week"),
        ("عطلة", "holiday"),
        ("رحلة", "trip"),
        ("تذكرة", "ticket"),
        ("حقيبة", "bag"),
        ("جواز", "passport"),
        ("عنوان", "address"),
        ("رسالة", "letter / message"),
        ("هاتف", "telephone"),
        ("رقم الهاتف", "phone number"),
        ("انترنت", "internet"),
        ("حاسوب", "computer"),
        ("صورة", "picture"),
        ("خبر", "news"),
        ("صحيفة", "newspaper"),
        ("فيلم", "film"),
        ("موسيقى", "music"),
        ("رياضة", "sport"),
        ("مباراة", "match"),
        ("طقس", "weather"),
        ("مطر", "rain"),
        ("شمس", "sun"),
        ("رياح", "wind"),
        ("ثلج", "snow"),
        ("ربيع", "spring"),
        ("صيف", "summer"),
        ("خريف", "autumn"),
        ("شتاء", "winter"),
        ("شمال", "north"),
        ("جنوب", "south"),
        ("شرق", "east"),
        ("غرب", "west"),
        ("يمين", "right"),
        ("يسار", "left"),
        ("وسط", "middle"),
        ("مكان", "place"),
        ("بلد", "country"),
        ("دولة", "state / country"),
        ("حكومة", "government"),
        ("قانون", "law"),
        ("مشكلة", "problem"),
        ("حل", "solution"),
        ("سبب", "reason"),
        ("نتيجة", "result"),
        ("فكرة", "idea"),
        ("راي", "opinion"),
        ("رأي", "opinion"),
        ("حقيقة", "truth / fact"),
        ("ممكن", "possible"),
        ("مهم", "important"),
        ("ضروري", "necessary"),
        ("مشهور", "famous"),
        ("غني", "rich"),
        ("فقير", "poor"),
        ("نظيف", "clean"),
        ("وسخ", "dirty"),
        ("سريع", "fast"),
        ("بطيء", "slow"),
        ("قوي", "strong"),
        ("ضعيف", "weak"),
        ("صحيح", "correct / healthy"),
        ("خطأ", "mistake"),
        ("اخر", "other / last"),
        ("آخر", "other / last"),
        ("نفس", "same / self"),
        ("كل يوم", "every day"),
        ("احيانا", "sometimes"),
        ("أحيانا", "sometimes"),
        ("دائما", "always"),
        ("ابدا", "never"),
        ("أبدا", "never"),
        ("غالبا", "often"),
        ("فقط", "only"),
        ("تقريبا", "approximately"),
        ("مثلا", "for example"),
        ("لان", "because"),
        ("لأن", "because"),
        ("اذا", "if"),
        ("إذا", "if"),
        ("عندما", "when"),
        ("بعد ذلك", "after that"),
        ("لذلك", "therefore"),
        ("سواء", "whether"),
        ("اشترى", "to buy"),
        ("باع", "to sell"),
        ("دفع", "to pay"),
        ("كلف", "to cost"),
        ("سافر", "to travel"),
        ("وصل", "to arrive"),
        ("غادر", "to leave"),
        ("انتظر", "to wait"),
        ("ركب", "to ride"),
        ("قاد", "to drive"),
        ("مشي", "to walk"),
        ("مشى", "to walk"),
        ("جرى", "to run"),
        ("سبح", "to swim"),
        ("طبخ", "to cook"),
        ("غسل", "to wash"),
        ("لبس", "to wear"),
        ("خلع", "to take off"),
        ("احضر", "to bring"),
        ("أحضر", "to bring"),
        ("ارسل", "to send"),
        ("أرسل", "to send"),
        ("استقبل", "to receive"),
        ("كلم", "to speak to"),
        ("تحدث", "to speak"),
        ("سال", "to ask"),
        ("سأل", "to ask"),
        ("اجاب", "to answer"),
        ("أجاب", "to answer"),
        ("ساعد", "to help"),
        ("جرب", "to try"),
        ("بدأ", "to begin"),
        ("بدا", "to begin"),
        ("انتهى", "to finish"),
        ("استمر", "to continue"),
        ("تغير", "to change"),
        ("غير", "to change / other"),
        ("قرر", "to decide"),
        ("فكر", "to think"),
        ("تذكر", "to remember"),
        ("نسي", "to forget"),
        ("نسى", "to forget"),
        ("ضحك", "to laugh"),
        ("بكى", "to cry"),
        ("خاف", "to fear"),
        ("امل", "to hope"),
        ("أمل", "to hope"),
        ("نجح", "to succeed"),
        ("فشل", "to fail"),
        ("درس", "to study / lesson"),
        ("علم", "to teach / knowledge"),
        ("تعلم", "to learn"),
        ("شرح", "to explain"),
        ("ترجم", "to translate"),
        ("بحث", "to search"),
        ("وجد", "to find"),
        ("خسر", "to lose"),
        ("ربح", "to win / profit"),
        ("بنى", "to build"),
        ("كسر", "to break"),
        ("صلح", "to repair"),
        ("استعمل", "to use"),
        ("استخدم", "to use"),
        ("احتاج", "to need"),
        ("أحتاج", "to need"),
        ("فضل", "to prefer"),
        ("أحب", "to love"),
        ("كره", "to hate"),
        ("عاش", "to live"),
        ("مات", "to die"),
        ("ولد", "to be born / boy"),
        ("زوج", "husband"),
        ("زوجة", "wife"),
        ("جد", "grandfather"),
        ("جدة", "grandmother"),
        ("عم", "paternal uncle"),
        ("خال", "maternal uncle"),
        ("جار", "neighbor"),
        ("ضيف", "guest"),
        ("صاحب", "owner / friend"),
        ("زبون", "customer"),
        ("شرطي", "police officer"),
        ("مهندس", "engineer"),
        ("محامي", "lawyer"),
        ("ممرض", "nurse"),
        ("طاهي", "cook"),
        ("سائق", "driver"),
        ("فلاح", "farmer"),
        ("عامل", "worker"),
        ("مدير", "manager"),
        ("جامعة", "university"),
        ("كلية", "college"),
        ("مكتبة", "library / bookstore"),
        ("متحف", "museum"),
        ("مسجد", "mosque"),
        ("كنيسة", "church"),
        ("حديقة", "garden / park"),
        ("شاطئ", "beach"),
        ("جبل", "mountain"),
        ("نهر", "river"),
        ("بحر", "sea"),
        ("صحراء", "desert"),
        ("غابة", "forest"),
        ("جزيرة", "island"),
        ("جسر", "bridge"),
        ("طريق", "road"),
        ("سيارة اجرة", "taxi"),
        ("دراجة", "bicycle"),
        ("سفينة", "ship"),
        ("ملابس", "clothes"),
        ("قميص", "shirt"),
        ("فستان", "dress"),
        ("حذاء", "shoe"),
        ("معطف", "coat"),
        ("قبعة", "hat"),
        ("ساعة يد", "wristwatch"),
        ("نظارة", "glasses"),
        ("خبز", "bread"),
        ("جبن", "cheese"),
        ("زبدة", "butter"),
        ("زيت", "oil"),
        ("بيض", "eggs"),
        ("دجاج", "chicken"),
        ("شوربة", "soup"),
        ("سلطة", "salad"),
        ("حلوى", "dessert / sweets"),
        ("عصير", "juice"),
        ("نبيذ", "wine"),
        ("جائع", "hungry"),
        ("عطشان", "thirsty"),
        ("تعبان", "tired"),
        ("نائم", "asleep"),
        ("مستعجل", "in a hurry"),
        ("مشغول", "busy"),
        ("فارغ", "empty"),
        ("كامل", "complete"),
        ("نصف", "half"),
        ("ربع", "quarter"),
        ("سعر", "price"),
        ("رخيص", "cheap"),
        ("غالي", "expensive"),
        ("مجاني", "free"),
        ("فاتورة", "bill"),
        ("بنك", "bank"),
        ("بطاقة", "card"),
        ("جواز سفر", "passport"),
        ("تاشيرة", "visa"),
        ("تأشيرة", "visa"),
    ],
)

add(
    "B1",
    [
        ("ان", "that / indeed"),
        ("إن", "indeed"),
        ("أن", "that"),
        ("الذي", "who / which (masc)"),
        ("التي", "who / which (fem)"),
        ("الذين", "who (pl)"),
        ("رغم", "despite"),
        ("بينما", "while"),
        ("حتى", "until / even"),
        ("حيث", "where / whereas"),
        ("كي", "in order that"),
        ("لو", "if (counterfactual)"),
        ("لقد", "indeed (past)"),
        ("قد", "may / already"),
        ("سوف", "will"),
        ("لم", "did not"),
        ("لن", "will not"),
        ("منذ", "since"),
        ("خلال", "during"),
        ("ضد", "against"),
        ("نحو", "toward"),
        ("حول", "around / about"),
        ("حسب", "according to"),
        ("بدون", "without"),
        ("سوى", "except"),
        ("خصوصا", "especially"),
        ("عموما", "in general"),
        ("طبعا", "of course"),
        ("ربما", "perhaps"),
        ("بالتاكيد", "certainly"),
        ("بالتأكيد", "certainly"),
        ("للأسف", "unfortunately"),
        ("لحسن الحظ", "fortunately"),
        ("مجتمع", "society"),
        ("ثقافة", "culture"),
        ("تاريخ", "history / date"),
        ("سياسة", "politics"),
        ("اقتصاد", "economy"),
        ("بيئة", "environment"),
        ("تعليم", "education"),
        ("صحة", "health"),
        ("حقوق", "rights"),
        ("حرية", "freedom"),
        ("عدالة", "justice"),
        ("امن", "security"),
        ("أمن", "security"),
        ("سلام", "peace"),
        ("حرب", "war"),
        ("جيش", "army"),
        ("شرطة", "police"),
        ("جريمة", "crime"),
        ("قانون", "law"),
        ("محكمة", "court"),
        ("انتخابات", "elections"),
        ("رئيس", "president / chief"),
        ("وزير", "minister"),
        ("برلمان", "parliament"),
        ("مواطن", "citizen"),
        ("سكان", "inhabitants"),
        ("هجرة", "migration"),
        ("لاجئ", "refugee"),
        ("تنمية", "development"),
        ("تكنولوجيا", "technology"),
        ("علم", "science / knowledge"),
        ("بحث", "research"),
        ("تجربة", "experiment / experience"),
        ("نتيجة", "result"),
        ("سبب", "cause"),
        ("تأثير", "effect / influence"),
        ("هدف", "goal"),
        ("خطة", "plan"),
        ("مشروع", "project"),
        ("شركة", "company"),
        ("سوق العمل", "job market"),
        ("راتب", "salary"),
        ("عقد", "contract"),
        ("اجتماع", "meeting"),
        ("موعد", "appointment"),
        ("فرصة", "opportunity"),
        ("خطر", "danger"),
        ("ازمة", "crisis"),
        ("أزمة", "crisis"),
        ("حل", "solution"),
        ("نقاش", "discussion"),
        ("حوار", "dialogue"),
        ("خلاف", "disagreement"),
        ("اتفاق", "agreement"),
        ("شرط", "condition"),
        ("قاعدة", "rule / base"),
        ("نظام", "system"),
        ("مستوى", "level"),
        ("جودة", "quality"),
        ("كمية", "quantity"),
        ("نسبة", "percentage / ratio"),
        ("معدل", "average / rate"),
        ("احصاء", "statistic"),
        ("إحصاء", "statistic"),
        ("معلومات", "information"),
        ("بيانات", "data"),
        ("مصدر", "source"),
        ("دليل", "evidence / guide"),
        ("برهان", "proof"),
        ("شك", "doubt"),
        ("ثقة", "trust"),
        ("امل", "hope"),
        ("خوف", "fear"),
        ("قلق", "worry"),
        ("غضب", "anger"),
        ("فرح", "joy"),
        ("حزن", "sadness"),
        ("دهشة", "surprise"),
        ("اهتمام", "interest"),
        ("مسؤولية", "responsibility"),
        ("واجب", "duty / homework"),
        ("حق", "right / truth"),
        ("ظلم", "injustice"),
        ("صدق", "honesty"),
        ("كذب", "lying"),
        ("شجاع", "brave"),
        ("جبان", "cowardly"),
        ("كريم", "generous"),
        ("بخيل", "stingy"),
        ("صبور", "patient"),
        ("كسول", "lazy"),
        ("نشيط", "active"),
        ("ذكي", "intelligent"),
        ("غبي", "stupid"),
        ("واثق", "confident"),
        ("متردد", "hesitant"),
        ("مستقل", "independent"),
        ("مشترك", "shared / common"),
        ("خاص", "private / special"),
        ("عام", "public / general"),
        ("رسمي", "official"),
        ("شعبي", "popular"),
        ("محلي", "local"),
        ("دولي", "international"),
        ("عالمي", "global / worldwide"),
        ("حديث", "modern / conversation"),
        ("تقليدي", "traditional"),
        ("اصلي", "original / authentic"),
        ("أصلي", "original / authentic"),
        ("مصطنع", "artificial"),
        ("طبيعي", "natural"),
        ("اصطناعي", "synthetic"),
        ("استمر", "to continue"),
        ("توقف", "to stop"),
        ("حاول", "to try"),
        ("تمكن", "to be able to"),
        ("استطاع", "to be able"),
        ("وجب", "to be necessary"),
        ("يجب", "must"),
        ("ينبغي", "ought to"),
        ("يجوز", "it is permitted"),
        ("يمنع", "to forbid"),
        ("سمح", "to allow"),
        ("رفض", "to refuse"),
        ("قبل", "to accept / before"),
        ("وافق", "to agree"),
        ("اعترض", "to object"),
        ("اعترض", "to object"),
        ("اقترح", "to suggest"),
        ("اقترح", "to suggest"),
        ("نصح", "to advise"),
        ("حذر", "to warn"),
        ("وعد", "to promise"),
        ("كذب", "to lie"),
        ("صدق", "to believe / be truthful"),
        ("شك", "to doubt"),
        ("اثبت", "to prove"),
        ("أثبت", "to prove"),
        ("اظهر", "to show"),
        ("أظهر", "to show"),
        ("اخفى", "to hide"),
        ("أخفى", "to hide"),
        ("اكتشف", "to discover"),
        ("اخترع", "to invent"),
        ("انتج", "to produce"),
        ("أنتج", "to produce"),
        ("استهلك", "to consume"),
        ("وفر", "to save / provide"),
        ("أنفق", "to spend"),
        ("انفق", "to spend"),
        ("استثمر", "to invest"),
        ("ربح", "to profit"),
        ("خسر", "to lose"),
        ("ادار", "to manage"),
        ("أدار", "to manage"),
        ("نظم", "to organize"),
        ("خطط", "to plan"),
        ("نفذ", "to implement"),
        ("حقق", "to achieve"),
        ("فشل", "to fail"),
        ("تحسن", "to improve"),
        ("ساء", "to worsen"),
        ("زاد", "to increase"),
        ("قل", "to decrease"),
        ("ارتفع", "to rise"),
        ("انخفض", "to fall"),
        ("شمل", "to include"),
        ("استثنى", "to exclude"),
        ("قارن", "to compare"),
        ("اختار", "to choose"),
        ("بدل", "to replace"),
        ("أضاف", "to add"),
        ("اضاف", "to add"),
        ("حذف", "to delete"),
        ("كرر", "to repeat"),
        ("لخص", "to summarize"),
        ("وصف", "to describe"),
        ("عرف", "to define / know"),
        ("ترجم", "to translate"),
        ("نشر", "to publish"),
        ("طبع", "to print"),
        ("سجل", "to record / register"),
        ("وقع", "to sign / happen"),
        ("حدث", "to happen"),
        ("جرى", "to take place / run"),
        ("اصبح", "to become"),
        ("أصبح", "to become"),
        ("صار", "to become"),
        ("ظل", "to remain"),
        ("بقى", "to remain"),
        ("بقي", "to remain"),
        ("عاد", "to return"),
        ("ترك", "to leave"),
        ("لحق", "to catch up / follow"),
        ("تبع", "to follow"),
        ("قاد", "to lead"),
        ("شارك", "to participate"),
        ("انضم", "to join"),
        ("اعتذر", "to apologize"),
        ("شكر", "to thank"),
        ("هنأ", "to congratulate"),
        ("دعا", "to invite / call"),
        ("زار", "to visit"),
        ("استضاف", "to host"),
        ("احتفل", "to celebrate"),
        ("تزوج", "to marry"),
        ("طلق", "to divorce"),
        ("ربي", "to raise (a child)"),
        ("ربى", "to raise"),
        ("اعتنى", "to take care of"),
        ("عالج", "to treat (medically)"),
        ("شفى", "to heal"),
        ("اصيب", "to be injured"),
        ("أصيب", "to be injured"),
        ("توفي", "to pass away"),
        ("ولد", "to give birth / boy"),
    ],
)

add(
    "B2",
    [
        ("بالرغم من", "despite"),
        ("على الرغم من", "despite"),
        ("فضلا عن", "in addition to"),
        ("بالإضافة إلى", "in addition to"),
        ("فيما يتعلق", "with regard to"),
        ("من ناحية", "on the one hand"),
        ("من جهة اخرى", "on the other hand"),
        ("بمعنى آخر", "in other words"),
        ("اي ان", "that is to say"),
        ("أي أن", "that is to say"),
        ("لا سيما", "especially"),
        ("مهما", "whatever / no matter"),
        ("كلما", "whenever / the more"),
        ("كأن", "as if"),
        ("ليت", "if only"),
        ("لعل", "perhaps / maybe"),
        ("حال", "circumstantial / state"),
        ("ظاهرة", "phenomenon"),
        ("مفهوم", "concept"),
        ("نظرية", "theory"),
        ("فرضية", "hypothesis"),
        ("منهج", "method / curriculum"),
        ("تحليل", "analysis"),
        ("تفسير", "interpretation"),
        ("تقييم", "evaluation"),
        ("نقد", "criticism"),
        ("جدل", "controversy"),
        ("خطاب", "discourse / speech"),
        ("رواية", "novel"),
        ("شعر", "poetry"),
        ("ادب", "literature"),
        ("أدب", "literature"),
        ("فن", "art"),
        ("فلسفة", "philosophy"),
        ("اخلاق", "ethics"),
        ("أخلاق", "ethics"),
        ("هوية", "identity"),
        ("انتماء", "belonging"),
        ("تمييز", "discrimination"),
        ("مساواة", "equality"),
        ("تنوع", "diversity"),
        ("اندماج", "integration"),
        ("عولمة", "globalization"),
        ("استدامة", "sustainability"),
        ("تغير المناخ", "climate change"),
        ("طاقة", "energy"),
        ("موارد", "resources"),
        ("بنية تحتية", "infrastructure"),
        ("ابتكار", "innovation"),
        ("رقمي", "digital"),
        ("ذكاء اصطناعي", "artificial intelligence"),
        ("خصوصية", "privacy"),
        ("شفافية", "transparency"),
        ("فساد", "corruption"),
        ("اصلاح", "reform"),
        ("إصلاح", "reform"),
        ("استقرار", "stability"),
        ("اضطراب", "unrest / disorder"),
        ("توتر", "tension"),
        ("مفاوضات", "negotiations"),
        ("هدنة", "truce"),
        ("معاهدة", "treaty"),
        ("سيادة", "sovereignty"),
        ("ديمقراطية", "democracy"),
        ("استبداد", "tyranny"),
        ("رقابة", "censorship / oversight"),
        ("اعلام", "media"),
        ("إعلام", "media"),
        ("شائعة", "rumor"),
        ("تغطية", "coverage"),
        ("مراسل", "correspondent"),
        ("تحقيق", "investigation"),
        ("شهادة", "testimony / certificate"),
        ("ادانة", "condemnation"),
        ("إدانة", "condemnation"),
        ("براءة", "innocence"),
        ("عقوبة", "punishment"),
        ("سجن", "prison"),
        ("افراج", "release"),
        ("إفراج", "release"),
        ("لجأ", "to resort / seek asylum"),
        ("ناشد", "to appeal to"),
        ("طالب", "to demand / student"),
        ("فرض", "to impose"),
        ("الغى", "to cancel"),
        ("ألغى", "to cancel"),
        ("عدل", "to amend"),
        ("سن", "to enact (a law)"),
        ("انتخب", "to elect"),
        ("عين", "to appoint"),
        ("أقيل", "to be dismissed"),
        ("استقال", "to resign"),
        ("ترشح", "to run (for office)"),
        ("صوت", "to vote / voice"),
        ("احتج", "to protest"),
        ("تظاهر", "to demonstrate"),
        ("قمع", "to suppress"),
        ("اضطهد", "to persecute"),
        ("ميز", "to discriminate / distinguish"),
        ("همش", "to marginalize"),
        ("دمج", "to integrate"),
        ("عزز", "to strengthen"),
        ("ضعف", "to weaken"),
        ("ساهم", "to contribute"),
        ("افضى", "to lead to"),
        ("أفضى", "to lead to"),
        ("ترتب", "to result"),
        ("انطوى", "to involve"),
        ("اقتضى", "to require"),
        ("استلزم", "to necessitate"),
        ("افترض", "to assume"),
        ("استنتج", "to conclude"),
        ("استدل", "to infer"),
        ("دحض", "to refute"),
        ("فند", "to rebut"),
        ("أيد", "to support"),
        ("ايد", "to support"),
        ("عارض", "to oppose"),
        ("تبنى", "to adopt"),
        ("تخلى", "to abandon"),
        ("سعى", "to strive"),
        ("حرص", "to be keen"),
        ("ادعى", "to claim"),
        ("ادعى", "to claim"),
        ("زعم", "to allege"),
        ("نفى", "to deny"),
        ("أكد", "to confirm"),
        ("اكد", "to confirm"),
        ("صرح", "to declare"),
        ("اوما", "to hint"),
        ("أوحى", "to suggest / inspire"),
        ("اوحي", "to suggest"),
        ("الهم", "to inspire"),
        ("ألهم", "to inspire"),
        ("اثر", "to influence"),
        ("أثر", "to influence"),
        ("تشكل", "to constitute / be formed"),
        ("مثل", "to represent"),
        ("عكس", "to reflect"),
        ("برز", "to emerge"),
        ("ساد", "to prevail"),
        ("ندر", "to be rare"),
        ("شاع", "to become widespread"),
        ("تراجع", "to decline"),
        ("تفوق", "to surpass"),
        ("عانى", "to suffer"),
        ("كابد", "to endure"),
        ("تغلب", "to overcome"),
        ("واجه", "to face"),
        ("تعامل", "to deal with"),
        ("تكيف", "to adapt"),
        ("تأقلم", "to acclimatize"),
        ("تاقلم", "to acclimatize"),
    ],
)

# Common triliteral (and a few quadriliteral) roots with a short English gloss.
for letters, meaning in [
    ("كتب", "write"),
    ("قرا", "read"),
    ("قرا", "read"),
    ("درس", "study"),
    ("علم", "know / teach"),
    ("فهم", "understand"),
    ("عرف", "know"),
    ("قال", "say"),
    ("كلم", "speak"),
    ("حدث", "happen / speak"),
    ("سمع", "hear"),
    ("راي", "see"),
    ("نظر", "look"),
    ("ذهب", "go"),
    ("جاء", "come"),
    ("اتي", "come"),
    ("وصل", "arrive"),
    ("خرج", "exit"),
    ("دخل", "enter"),
    ("جلس", "sit"),
    ("وقف", "stand"),
    ("قام", "rise"),
    ("قعد", "sit"),
    ("نام", "sleep"),
    ("اكل", "eat"),
    ("شرب", "drink"),
    ("طبخ", "cook"),
    ("فتح", "open"),
    ("غلق", "close"),
    ("كتب", "write"),
    ("قرا", "read"),
    ("حسب", "count / reckon"),
    ("عمل", "do / work"),
    ("فعل", "do"),
    ("جعل", "make"),
    ("وضع", "put"),
    ("اخذ", "take"),
    ("ترك", "leave"),
    ("وجد", "find"),
    ("طلب", "request"),
    ("بحث", "search"),
    ("حصل", "obtain"),
    ("قدم", "offer / come forward"),
    ("رجع", "return"),
    ("عاد", "return"),
    ("سافر", "travel"),
    ("سكن", "dwell"),
    ("عيش", "live"),
    ("موت", "die"),
    ("ولد", "be born"),
    ("حبب", "love"),
    ("حب", "love"),
    ("كره", "hate"),
    ("خوف", "fear"),
    ("امن", "be safe"),
    ("سلم", "be safe / greet"),
    ("نجح", "succeed"),
    ("فشل", "fail"),
    ("قدر", "be able"),
    ("مكن", "enable"),
    ("ريد", "want"),
    ("راد", "want"),
    ("حتاج", "need"),
    ("بدأ", "begin"),
    ("بدء", "begin"),
    ("تمم", "complete"),
    ("كمل", "complete"),
    ("غير", "change"),
    ("بدل", "replace"),
    ("زيد", "increase"),
    ("زاد", "increase"),
    ("قلل", "decrease"),
    ("كبر", "grow"),
    ("صغر", "be small"),
    ("طول", "be long"),
    ("قصر", "be short"),
    ("حسن", "be good"),
    ("سوء", "be bad"),
    ("جمل", "be beautiful"),
    ("قبح", "be ugly"),
    ("سهل", "be easy"),
    ("صعب", "be hard"),
    ("قرب", "be near"),
    ("بعد", "be far"),
    ("كثر", "be many"),
    ("قلل", "be few"),
    ("جمع", "gather"),
    ("فرق", "separate"),
    ("وصل", "connect"),
    ("قطع", "cut"),
    ("كسر", "break"),
    ("صلح", "repair"),
    ("بنى", "build"),
    ("بني", "build"),
    ("هدم", "demolish"),
    ("حمل", "carry"),
    ("رفع", "lift"),
    ("خفض", "lower"),
    ("دفع", "pay / push"),
    ("سحب", "pull"),
    ("ضرب", "hit"),
    ("قتل", "kill"),
    ("حيا", "live"),
    ("شفي", "heal"),
    ("مرض", "be sick"),
    ("طبب", "treat"),
    ("لبس", "wear"),
    ("خلع", "remove"),
    ("غسل", "wash"),
    ("نظف", "clean"),
    ("باع", "sell"),
    ("شري", "buy"),
    ("شرى", "buy"),
    ("كلف", "cost"),
    ("ثمن", "price"),
    ("ملك", "own"),
    ("خسر", "lose"),
    ("ربح", "profit"),
    ("حكم", "rule / judge"),
    ("قضي", "judge / spend"),
    ("عدل", "be just"),
    ("ظلم", "wrong"),
    ("شهد", "witness"),
    ("كذب", "lie"),
    ("صدق", "be truthful"),
    ("امن", "believe"),
    ("شكر", "thank"),
    ("حمد", "praise"),
    ("عبد", "worship"),
    ("صلي", "pray"),
    ("صلا", "pray"),
    ("صوم", "fast"),
    ("حجج", "make pilgrimage"),
    ("قرء", "read"),
    ("حفظ", "memorize / protect"),
    ("نسي", "forget"),
    ("ذكر", "remember"),
    ("فكر", "think"),
    ("علم", "know"),
    ("جهل", "be ignorant"),
    ("درس", "study"),
    ("شرح", "explain"),
    ("ترجم", "translate"),
    ("كتب", "write"),
    ("رسم", "draw"),
    ("صور", "depict"),
    ("غني", "sing / be rich"),
    ("لعب", "play"),
    ("ربح", "win"),
    ("سبق", "precede"),
    ("تبع", "follow"),
    ("قود", "lead"),
    ("قاد", "lead"),
    ("امر", "command"),
    ("طاع", "obey"),
    ("عصى", "disobey"),
    ("سمح", "allow"),
    ("منع", "prevent"),
    ("وجب", "be necessary"),
    ("جوز", "permit"),
    ("حرم", "forbid"),
    ("حل", "solve / be lawful"),
    ("عقد", "contract"),
    ("ربط", "tie"),
    ("فكك", "untie"),
    ("ستر", "cover"),
    ("كشف", "uncover"),
    ("ظهر", "appear"),
    ("خفي", "be hidden"),
    ("بان", "become clear"),
    ("وضح", "clarify"),
    ("بين", "make clear"),
    ("خبر", "inform"),
    ("نبا", "news"),
    ("علن", "announce"),
    ("نشر", "spread"),
    ("طبع", "print"),
    ("سجل", "record"),
    ("وقع", "fall / sign"),
    ("حدث", "occur"),
    ("جرى", "flow / happen"),
    ("صار", "become"),
    ("كون", "be"),
    ("كان", "be"),
    ("بقى", "remain"),
    ("بقي", "remain"),
    ("دام", "last"),
    ("فني", "perish"),
    ("خلق", "create"),
    ("صنع", "make"),
    ("عمل", "work"),
    ("خدم", "serve"),
    ("ساعد", "help"),
    ("عون", "aid"),
    ("نصر", "give victory"),
    ("هزم", "defeat"),
    ("حرب", "wage war"),
    ("سلم", "make peace"),
    ("صلح", "reconcile"),
    ("خصم", "oppose"),
    ("فقه", "understand (law)"),
    ("شرع", "legislate"),
    ("سنن", "enact"),
    ("نتج", "result"),
    ("سبب", "cause"),
    ("اثر", "affect"),
    ("غير", "alter"),
    ("طور", "develop"),
    ("نمي", "grow"),
    ("نما", "grow"),
    ("ضعف", "weaken"),
    ("قوي", "strengthen"),
    ("مكن", "enable"),
    ("عجز", "be unable"),
    ("يسر", "be easy"),
    ("عسر", "be difficult"),
]:
    root(letters, meaning)


def main() -> None:
    vocab = {lemma: band for lemma, (band, _) in PEDAGOGICAL.items()}
    gloss = {lemma: g for lemma, (_, g) in PEDAGOGICAL.items()}
    roots = {
        letters: {"letters": " ".join(letters), "meaning": meaning}
        for letters, meaning in ROOTS.items()
    }
    VOCAB_OUT.parent.mkdir(parents=True, exist_ok=True)
    GLOSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    ROOTS_OUT.parent.mkdir(parents=True, exist_ok=True)
    VOCAB_OUT.write_text(
        json.dumps(dict(sorted(vocab.items())), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    GLOSS_OUT.write_text(
        json.dumps(dict(sorted(gloss.items())), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    ROOTS_OUT.write_text(
        json.dumps(dict(sorted(roots.items())), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"vocab {len(vocab)} → {VOCAB_OUT}")
    print(f"gloss {len(gloss)} → {GLOSS_OUT}")
    print(f"roots {len(roots)} → {ROOTS_OUT}")


if __name__ == "__main__":
    main()
