#!/usr/bin/env python3
"""Build CEFR-banded Italian vocab + it→en gloss JSON from a pedagogical core.

Optional frequency ranks from data/raw/it_freq.txt (one word per line) fill
gaps the pedagogical list does not cover. Pedagogical bands always win.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FREQ_PATH = ROOT / "data" / "raw" / "it_freq.txt"
VOCAB_OUT = ROOT / "data" / "vocab" / "it_cefr.json"
GLOSS_OUT = ROOT / "data" / "gloss" / "it_en.json"

PEDAGOGICAL: dict[str, tuple[str, str]] = {}


def add(level: str, pairs: list[tuple[str, str]]) -> None:
    for lemma, gloss in pairs:
        lemma = lemma.strip().lower()
        if lemma and lemma not in PEDAGOGICAL:
            PEDAGOGICAL[lemma] = (level, gloss.strip())


add(
    "A1",
    [
        ("io", "I"),
        ("tu", "you (informal)"),
        ("lui", "he"),
        ("lei", "she / you (formal)"),
        ("noi", "we"),
        ("voi", "you (plural)"),
        ("loro", "they"),
        ("me", "me"),
        ("te", "you (object)"),
        ("mio", "my"),
        ("tuo", "your (informal)"),
        ("suo", "his / her / your (formal)"),
        ("nostro", "our"),
        ("vostro", "your (plural)"),
        ("questo", "this"),
        ("quello", "that"),
        ("un", "a / an"),
        ("uno", "a / one (masc)"),
        ("una", "a (fem)"),
        ("il", "the (masc)"),
        ("lo", "the (masc, s+cons)"),
        ("la", "the (fem)"),
        ("i", "the (masc pl)"),
        ("gli", "the (masc pl)"),
        ("le", "the (fem pl)"),
        ("l'", "the (elided)"),
        ("essere", "to be"),
        ("avere", "to have"),
        ("fare", "to do / make"),
        ("andare", "to go"),
        ("vado", "I go"),
        ("stare", "to stay / be"),
        ("dare", "to give"),
        ("dire", "to say"),
        ("venire", "to come"),
        ("vedere", "to see"),
        ("sapere", "to know (a fact)"),
        ("volere", "to want"),
        ("potere", "can / to be able"),
        ("dovere", "must / to have to"),
        ("mangiare", "to eat"),
        ("bere", "to drink"),
        ("parlare", "to speak"),
        ("leggere", "to read"),
        ("scrivere", "to write"),
        ("abitare", "to live (in a place)"),
        ("lavorare", "to work"),
        ("studiare", "to study"),
        ("capire", "to understand"),
        ("aprire", "to open"),
        ("chiudere", "to close"),
        ("entrare", "to enter"),
        ("uscire", "to go out"),
        ("arrivare", "to arrive"),
        ("partire", "to leave"),
        ("chiamare", "to call"),
        ("guardare", "to look"),
        ("ascoltare", "to listen"),
        ("piacere", "to like / please"),
        ("servire", "to need / serve"),
        ("mettere", "to put"),
        ("prendere", "to take"),
        ("portare", "to bring / wear"),
        ("trovare", "to find"),
        ("cercare", "to look for"),
        ("comprare", "to buy"),
        ("compro", "I buy"),
        ("vendere", "to sell"),
        ("pagare", "to pay"),
        ("costare", "to cost"),
        ("usare", "to use"),
        ("aiutare", "to help"),
        ("aspettare", "to wait"),
        ("camminare", "to walk"),
        ("correre", "to run"),
        ("dormire", "to sleep"),
        ("svegliare", "to wake"),
        ("lavare", "to wash"),
        ("cucinare", "to cook"),
        ("pulire", "to clean"),
        ("giocare", "to play"),
        ("cantare", "to sing"),
        ("ballare", "to dance"),
        ("viaggiare", "to travel"),
        ("visitare", "to visit"),
        ("incontrare", "to meet"),
        ("conoscere", "to know (a person/place)"),
        ("ricordare", "to remember"),
        ("dimenticare", "to forget"),
        ("pensare", "to think"),
        ("credere", "to believe"),
        ("sperare", "to hope"),
        ("amare", "to love"),
        ("odiare", "to hate"),
        ("sì", "yes"),
        ("no", "no"),
        ("non", "not"),
        ("grazie", "thank you"),
        ("prego", "you're welcome / please"),
        ("ciao", "hi / bye"),
        ("buongiorno", "good morning"),
        ("buonasera", "good evening"),
        ("buonanotte", "good night"),
        ("scusa", "sorry (informal)"),
        ("scusi", "sorry (formal)"),
        ("per favore", "please"),
        ("perpiacere", "please"),
        ("ecco", "here is / there is"),
        ("eccomi", "here I am"),
        ("uomo", "man"),
        ("donna", "woman"),
        ("ragazzo", "boy"),
        ("ragazza", "girl"),
        ("bambino", "child"),
        ("persona", "person"),
        ("gente", "people"),
        ("amico", "friend"),
        ("amica", "friend (fem)"),
        ("famiglia", "family"),
        ("padre", "father"),
        ("madre", "mother"),
        ("papà", "dad"),
        ("mamma", "mom"),
        ("figlio", "son"),
        ("figlia", "daughter"),
        ("fratello", "brother"),
        ("sorella", "sister"),
        ("marito", "husband"),
        ("moglie", "wife"),
        ("nonno", "grandfather"),
        ("nonna", "grandmother"),
        ("zio", "uncle"),
        ("zia", "aunt"),
        ("nome", "name"),
        ("cognome", "surname"),
        ("età", "age"),
        ("anno", "year"),
        ("mese", "month"),
        ("settimana", "week"),
        ("giorno", "day"),
        ("oggi", "today"),
        ("ieri", "yesterday"),
        ("domani", "tomorrow"),
        ("mattina", "morning"),
        ("pomeriggio", "afternoon"),
        ("sera", "evening"),
        ("notte", "night"),
        ("ora", "hour / now"),
        ("minuto", "minute"),
        ("tempo", "time / weather"),
        ("lunedì", "Monday"),
        ("martedì", "Tuesday"),
        ("mercoledì", "Wednesday"),
        ("giovedì", "Thursday"),
        ("venerdì", "Friday"),
        ("sabato", "Saturday"),
        ("domenica", "Sunday"),
        ("gennaio", "January"),
        ("febbraio", "February"),
        ("marzo", "March"),
        ("aprile", "April"),
        ("maggio", "May"),
        ("giugno", "June"),
        ("luglio", "July"),
        ("agosto", "August"),
        ("settembre", "September"),
        ("ottobre", "October"),
        ("novembre", "November"),
        ("dicembre", "December"),
        ("casa", "house / home"),
        ("appartamento", "apartment"),
        ("stanza", "room"),
        ("camera", "bedroom"),
        ("cucina", "kitchen"),
        ("bagno", "bathroom"),
        ("sala", "living room / hall"),
        ("porta", "door"),
        ("finestra", "window"),
        ("tavolo", "table"),
        ("sedia", "chair"),
        ("letto", "bed"),
        ("libro", "book"),
        ("quaderno", "notebook"),
        ("penna", "pen"),
        ("matita", "pencil"),
        ("telefono", "telephone"),
        ("computer", "computer"),
        ("chiave", "key"),
        ("borsa", "bag"),
        ("soldi", "money"),
        ("euro", "euro"),
        ("prezzo", "price"),
        ("città", "city"),
        ("paese", "town / country"),
        ("via", "street"),
        ("piazza", "square"),
        ("strada", "road"),
        ("scuola", "school"),
        ("università", "university"),
        ("classe", "class"),
        ("lezione", "lesson"),
        ("esame", "exam"),
        ("lavoro", "work / job"),
        ("ufficio", "office"),
        ("negozio", "shop"),
        ("mercato", "market"),
        ("supermercato", "supermarket"),
        ("ristorante", "restaurant"),
        ("bar", "café / bar"),
        ("albergo", "hotel"),
        ("hotel", "hotel"),
        ("stazione", "station"),
        ("treno", "train"),
        ("autobus", "bus"),
        ("macchina", "car"),
        ("bicicletta", "bicycle"),
        ("aereo", "airplane"),
        ("biglietto", "ticket"),
        ("passaporto", "passport"),
        ("banco", "counter / desk"),
        ("cibo", "food"),
        ("colazione", "breakfast"),
        ("pranzo", "lunch"),
        ("cena", "dinner"),
        ("pane", "bread"),
        ("acqua", "water"),
        ("vino", "wine"),
        ("caffè", "coffee"),
        ("tè", "tea"),
        ("latte", "milk"),
        ("succo", "juice"),
        ("frutta", "fruit"),
        ("mela", "apple"),
        ("arancia", "orange"),
        ("banana", "banana"),
        ("verdura", "vegetables"),
        ("insalata", "salad"),
        ("pasta", "pasta"),
        ("pizza", "pizza"),
        ("riso", "rice"),
        ("carne", "meat"),
        ("pesce", "fish"),
        ("formaggio", "cheese"),
        ("uovo", "egg"),
        ("zucchero", "sugar"),
        ("sale", "salt"),
        ("olio", "oil"),
        ("gelato", "ice cream"),
        ("cioccolato", "chocolate"),
        ("corpo", "body"),
        ("testa", "head"),
        ("occhio", "eye"),
        ("mano", "hand"),
        ("piede", "foot"),
        ("cuore", "heart"),
        ("salute", "health"),
        ("medico", "doctor"),
        ("ospedale", "hospital"),
        ("farmacia", "pharmacy"),
        ("problema", "problem"),
        ("domanda", "question"),
        ("risposta", "answer"),
        ("parola", "word"),
        ("lingua", "language / tongue"),
        ("italiano", "Italian"),
        ("inglese", "English"),
        ("numero", "number"),
        ("uno", "one"),
        ("due", "two"),
        ("tre", "three"),
        ("quattro", "four"),
        ("cinque", "five"),
        ("sei", "six"),
        ("sette", "seven"),
        ("otto", "eight"),
        ("nove", "nine"),
        ("dieci", "ten"),
        ("venti", "twenty"),
        ("trenta", "thirty"),
        ("cento", "hundred"),
        ("mille", "thousand"),
        ("primo", "first"),
        ("secondo", "second"),
        ("ultimo", "last"),
        ("grande", "big"),
        ("piccolo", "small"),
        ("nuovo", "new"),
        ("fresco", "fresh"),
        ("vecchio", "old"),
        ("buono", "good"),
        ("bravo", "good (at) / kind"),
        ("bello", "beautiful"),
        ("brutto", "ugly"),
        ("lungo", "long"),
        ("corto", "short"),
        ("alto", "tall / high"),
        ("basso", "short / low"),
        ("giovane", "young"),
        ("felice", "happy"),
        ("triste", "sad"),
        ("stanco", "tired"),
        ("malato", "ill"),
        ("caldo", "hot"),
        ("freddo", "cold"),
        ("facile", "easy"),
        ("difficile", "difficult"),
        ("importante", "important"),
        ("interessante", "interesting"),
        ("possibile", "possible"),
        ("necessario", "necessary"),
        ("aperto", "open"),
        ("chiuso", "closed"),
        ("pieno", "full"),
        ("vuoto", "empty"),
        ("pulito", "clean"),
        ("sporco", "dirty"),
        ("veloce", "fast"),
        ("lento", "slow"),
        ("vicino", "near"),
        ("lontano", "far"),
        ("destro", "right (direction)"),
        ("sinistro", "left"),
        ("qui", "here"),
        ("qua", "here"),
        ("lì", "there"),
        ("là", "there"),
        ("dove", "where"),
        ("quando", "when"),
        ("come", "how / like"),
        ("perché", "why / because"),
        ("chi", "who"),
        ("che", "that / what"),
        ("cosa", "thing / what"),
        ("quale", "which"),
        ("quanto", "how much"),
        ("molto", "very / a lot"),
        ("tanto", "so much"),
        ("poco", "a little"),
        ("troppo", "too much"),
        ("più", "more"),
        ("meno", "less"),
        ("anche", "also"),
        ("sempre", "always"),
        ("mai", "never"),
        ("già", "already"),
        ("ancora", "still / yet / again"),
        ("ora", "now"),
        ("adesso", "now"),
        ("poi", "then"),
        ("dopo", "after"),
        ("prima", "before"),
        ("subito", "immediately"),
        ("tardi", "late"),
        ("presto", "soon / early"),
        ("bene", "well"),
        ("male", "badly"),
        ("così", "like this / so"),
        ("insieme", "together"),
        ("solo", "only / alone"),
        ("quasi", "almost"),
        ("forse", "maybe"),
        ("certo", "certainly / certain"),
        ("vero", "true"),
        ("giusto", "right / correct"),
        ("sbagliato", "wrong"),
        ("di", "of"),
        ("a", "to / at"),
        ("da", "from / by"),
        ("in", "in"),
        ("con", "with"),
        ("su", "on"),
        ("per", "for"),
        ("tra", "between"),
        ("fra", "between"),
        ("e", "and"),
        ("o", "or"),
        ("ma", "but"),
        ("però", "however"),
        ("se", "if"),
        ("come", "as / like"),
        ("c'è", "there is"),
        ("ci sono", "there are"),
        ("ci", "there / us"),
        ("ne", "of it / from there"),
        ("si", "oneself / one"),
        ("mi", "me (clitic)"),
        ("ti", "you (clitic)"),
        ("colore", "color"),
        ("bianco", "white"),
        ("nero", "black"),
        ("rosso", "red"),
        ("blu", "blue"),
        ("verde", "green"),
        ("giallo", "yellow"),
        ("arancione", "orange (color)"),
        ("grigio", "grey"),
        ("marrone", "brown"),
        ("sole", "sun"),
        ("luna", "moon"),
        ("cielo", "sky"),
        ("pioggia", "rain"),
        ("neve", "snow"),
        ("vento", "wind"),
        ("nuvola", "cloud"),
        ("mare", "sea"),
        ("montagna", "mountain"),
        ("fiume", "river"),
        ("albero", "tree"),
        ("fiore", "flower"),
        ("animale", "animal"),
        ("cane", "dog"),
        ("gatto", "cat"),
        ("uccello", "bird"),
        ("musica", "music"),
        ("film", "film"),
        ("foto", "photo"),
        ("giornale", "newspaper"),
        ("lettera", "letter"),
        ("email", "email"),
        ("indirizzo", "address"),
        ("numero", "number"),
        ("studente", "student"),
        ("studentessa", "student (fem)"),
        ("insegnante", "teacher"),
        ("professore", "professor"),
        ("professoressa", "professor (fem)"),
        ("signore", "sir / Mr"),
        ("signora", "madam / Mrs"),
        ("signorina", "miss"),
        ("cameriere", "waiter"),
        ("cameriera", "waitress"),
        ("cliente", "customer"),
        ("venditore", "seller"),
        ("vicino", "neighbour / near"),
        ("stanza", "room"),
        ("acqua", "water"),
        ("pane", "bread"),
        ("città", "city"),
    ],
)

add(
    "A2",
    [
        ("cominciare", "to begin"),
        ("iniziare", "to start"),
        ("finire", "to finish"),
        ("continuare", "to continue"),
        ("cambiare", "to change"),
        ("diventare", "to become"),
        ("rimanere", "to remain"),
        ("tornare", "to return"),
        ("salire", "to go up / get on"),
        ("scendere", "to go down / get off"),
        ("passare", "to pass / spend (time)"),
        ("succedere", "to happen"),
        ("accadere", "to happen"),
        ("sembrare", "to seem"),
        ("sentire", "to hear / feel"),
        ("provare", "to try / feel"),
        ("scegliere", "to choose"),
        ("decidere", "to decide"),
        ("preferire", "to prefer"),
        ("offrire", "to offer"),
        ("ricevere", "to receive"),
        ("inviare", "to send"),
        ("mandare", "to send"),
        ("prenotare", "to book"),
        ("ordinare", "to order"),
        ("chiedere", "to ask"),
        ("rispondere", "to answer"),
        ("spiegare", "to explain"),
        ("mostrare", "to show"),
        ("presentare", "to introduce / present"),
        ("accompagnare", "to accompany"),
        ("lasciare", "to leave / let"),
        ("perdere", "to lose"),
        ("vincere", "to win"),
        ("guadagnare", "to earn"),
        ("spendere", "to spend (money)"),
        ("risparmiare", "to save (money)"),
        ("noleggiare", "to rent"),
        ("guidare", "to drive"),
        ("parcheggiare", "to park"),
        ("volare", "to fly"),
        ("nuotare", "to swim"),
        ("allenare", "to train"),
        ("praticare", "to practise"),
        ("imparare", "to learn"),
        ("insegnare", "to teach"),
        ("tradurre", "to translate"),
        ("ripetere", "to repeat"),
        ("correggere", "to correct"),
        ("sbagliare", "to make a mistake"),
        ("funzionare", "to work (function)"),
        ("rompere", "to break"),
        ("riparare", "to repair"),
        ("costruire", "to build"),
        ("organizzare", "to organize"),
        ("preparare", "to prepare"),
        ("festeggiare", "to celebrate"),
        ("augurare", "to wish"),
        ("salutare", "to greet"),
        ("abbracciare", "to hug"),
        ("baciare", "to kiss"),
        ("sposare", "to marry"),
        ("nascere", "to be born"),
        ("morire", "to die"),
        ("vivere", "to live"),
        ("crescere", "to grow"),
        ("viaggio", "trip"),
        ("vacanza", "holiday"),
        ("turismo", "tourism"),
        ("turista", "tourist"),
        ("aeroporto", "airport"),
        ("binario", "platform / track"),
        ("orario", "timetable / schedule"),
        ("ritardo", "delay"),
        ("prenotazione", "booking"),
        ("camera", "room (hotel)"),
        ("colazione", "breakfast"),
        ("conto", "bill / account"),
        ("mancia", "tip"),
        ("carta", "card / paper"),
        ("contante", "cash"),
        ("sconto", "discount"),
        ("offerta", "offer"),
        ("qualità", "quality"),
        ("quantità", "quantity"),
        ("misura", "size / measure"),
        ("taglia", "size (clothes)"),
        ("vestito", "dress / outfit"),
        ("maglietta", "t-shirt"),
        ("pantaloni", "trousers"),
        ("scarpa", "shoe"),
        ("cappotto", "coat"),
        ("ombrello", "umbrella"),
        ("tempo", "weather / time"),
        ("grado", "degree"),
        ("nuvoloso", "cloudy"),
        ("soleggiato", "sunny"),
        ("umido", "humid"),
        ("secco", "dry"),
        ("appuntamento", "appointment"),
        ("invito", "invitation"),
        ("festa", "party"),
        ("compleanno", "birthday"),
        ("regalo", "gift"),
        ("hobby", "hobby"),
        ("sport", "sport"),
        ("partita", "match / game"),
        ("squadra", "team"),
        ("cinema", "cinema"),
        ("teatro", "theatre"),
        ("museo", "museum"),
        ("concerto", "concert"),
        ("internet", "internet"),
        ("sito", "site"),
        ("messaggio", "message"),
        ("chiamata", "call"),
        ("notizia", "news (item)"),
        ("giornale", "newspaper"),
        ("rivista", "magazine"),
        ("pubblicità", "advertising"),
        ("ufficio", "office"),
        ("collega", "colleague"),
        ("capo", "boss"),
        ("impiego", "employment"),
        ("orario", "working hours"),
        ("pausa", "break"),
        ("riunione", "meeting"),
        ("progetto", "project"),
        ("compito", "task / homework"),
        ("errore", "error"),
        ("soluzione", "solution"),
        ("motivo", "reason"),
        ("causa", "cause"),
        ("effetto", "effect"),
        ("risultato", "result"),
        ("esempio", "example"),
        ("differenza", "difference"),
        ("uguale", "equal / same"),
        ("diverso", "different"),
        ("stesso", "same"),
        ("altro", "other"),
        ("ogni", "each / every"),
        ("tutto", "all / everything"),
        ("niente", "nothing"),
        ("nessuno", "nobody"),
        ("qualcuno", "someone"),
        ("qualcosa", "something"),
        ("qualche", "some"),
        ("alcuno", "some / any"),
        ("entrambi", "both"),
        ("durante", "during"),
        ("mentre", "while"),
        ("fino", "until"),
        ("da", "since / from"),
        ("fa", "ago"),
        ("circa", "about / approximately"),
        ("almeno", "at least"),
        ("soprattutto", "especially"),
        ("invece", "instead"),
        ("comunque", "anyway"),
        ("infatti", "in fact"),
        ("quindi", "so / therefore"),
        ("allora", "then / so"),
        ("dunque", "therefore"),
        ("perciò", "that's why"),
        ("però", "but / however"),
        ("anzi", "on the contrary"),
        ("cioè", "that is"),
        ("ad esempio", "for example"),
        ("fortunato", "lucky"),
        ("sfortunato", "unlucky"),
        ("nervoso", "nervous"),
        ("tranquillo", "calm"),
        ("occupato", "busy"),
        ("libero", "free"),
        ("disponibile", "available"),
        ("gentile", "kind"),
        ("educato", "polite"),
        ("scortese", "rude"),
        ("simpatico", "nice"),
        ("antipatico", "unpleasant"),
        ("famoso", "famous"),
        ("normale", "normal"),
        ("strano", "strange"),
        ("speciale", "special"),
        ("perfetto", "perfect"),
        ("terribile", "terrible"),
        ("ottimo", "excellent"),
        ("pessimo", "awful"),
        ("caro", "expensive / dear"),
        ("economico", "cheap"),
        ("gratis", "free of charge"),
        ("moderno", "modern"),
        ("antico", "ancient"),
        ("comodo", "comfortable"),
        ("scomodo", "uncomfortable"),
        ("sicuro", "safe / sure"),
        ("pericoloso", "dangerous"),
        ("rumoroso", "noisy"),
        ("silenzioso", "quiet"),
        ("affollato", "crowded"),
        ("vuoto", "empty"),
        ("internazionale", "international"),
        ("nazionale", "national"),
        ("locale", "local"),
        ("centrale", "central"),
        ("pubblico", "public"),
        ("privato", "private"),
    ],
)

add(
    "B1",
    [
        ("riuscire", "to succeed / manage"),
        ("smettere", "to stop"),
        ("evitare", "to avoid"),
        ("permettere", "to allow"),
        ("vietare", "to forbid"),
        ("consigliare", "to advise"),
        ("suggerire", "to suggest"),
        ("proporre", "to propose"),
        ("accettare", "to accept"),
        ("rifiutare", "to refuse"),
        ("convincere", "to convince"),
        ("dubitare", "to doubt"),
        ("immaginare", "to imagine"),
        ("supporre", "to suppose"),
        ("rendersi", "to realize (oneself)"),
        ("accorgersi", "to notice"),
        ("rendersi conto", "to realize"),
        ("ottenere", "to obtain"),
        ("raggiungere", "to reach"),
        ("superare", "to overcome / pass"),
        ("affrontare", "to face"),
        ("risolvere", "to solve"),
        ("migliorare", "to improve"),
        ("peggiorare", "to worsen"),
        ("aumentare", "to increase"),
        ("diminuire", "to decrease"),
        ("sviluppare", "to develop"),
        ("influenzare", "to influence"),
        ("dipendere", "to depend"),
        ("appartenere", "to belong"),
        ("contenere", "to contain"),
        ("includere", "to include"),
        ("escludere", "to exclude"),
        ("sostituire", "to replace"),
        ("confrontare", "to compare"),
        ("analizzare", "to analyze"),
        ("descrivere", "to describe"),
        ("raccontare", "to tell"),
        ("narrare", "to narrate"),
        ("citare", "to quote"),
        ("riassumere", "to summarize"),
        ("commentare", "to comment"),
        ("discutere", "to discuss"),
        ("litigare", "to argue"),
        ("scusarsi", "to apologize"),
        ("lamentarsi", "to complain"),
        ("preoccuparsi", "to worry"),
        ("divertirsi", "to have fun"),
        ("annoiare", "to bore"),
        ("entusiasmare", "to thrill"),
        ("deludere", "to disappoint"),
        ("sorprendere", "to surprise"),
        ("spaventare", "to frighten"),
        ("fidarsi", "to trust"),
        ("diffidare", "to distrust"),
        ("esperienza", "experience"),
        ("opinione", "opinion"),
        ("punto di vista", "point of view"),
        ("argomento", "topic / argument"),
        ("discussione", "discussion"),
        ("accordo", "agreement"),
        ("disaccordo", "disagreement"),
        ("vantaggio", "advantage"),
        ("svantaggio", "disadvantage"),
        ("conseguenza", "consequence"),
        ("scopo", "purpose"),
        ("obiettivo", "goal"),
        ("tentativo", "attempt"),
        ("successo", "success"),
        ("fallimento", "failure"),
        ("opportunità", "opportunity"),
        ("possibilità", "possibility"),
        ("capacità", "ability"),
        ("difficoltà", "difficulty"),
        ("limite", "limit"),
        ("regola", "rule"),
        ("diritto", "right (legal)"),
        ("dovere", "duty"),
        ("responsabilità", "responsibility"),
        ("scelta", "choice"),
        ("decisione", "decision"),
        ("comportamento", "behaviour"),
        ("abitudine", "habit"),
        ("stile", "style"),
        ("ambiente", "environment / setting"),
        ("società", "society"),
        ("comunità", "community"),
        ("cultura", "culture"),
        ("tradizione", "tradition"),
        ("valore", "value"),
        ("identità", "identity"),
        ("origine", "origin"),
        ("passato", "past"),
        ("presente", "present"),
        ("futuro", "future"),
        ("memoria", "memory"),
        ("ricordo", "recollection"),
        ("sogno", "dream"),
        ("paura", "fear"),
        ("coraggio", "courage"),
        ("fiducia", "trust"),
        ("speranza", "hope"),
        ("felicità", "happiness"),
        ("tristezza", "sadness"),
        ("rabbia", "anger"),
        ("sorpresa", "surprise"),
        ("orgoglio", "pride"),
        ("vergogna", "shame"),
        ("invidia", "envy"),
        ("gelosia", "jealousy"),
        ("amicizia", "friendship"),
        ("relazione", "relationship"),
        ("coppia", "couple"),
        ("matrimonio", "marriage"),
        ("divorzio", "divorce"),
        ("infanzia", "childhood"),
        ("adolescenza", "adolescence"),
        ("gioventù", "youth"),
        ("vecchiaia", "old age"),
        ("carriera", "career"),
        ("stipendio", "salary"),
        ("disoccupazione", "unemployment"),
        ("contratto", "contract"),
        ("orario", "schedule"),
        ("straordinario", "overtime"),
        ("ferie", "paid leave"),
        ("malattia", "illness"),
        ("cura", "care / treatment"),
        ("sintomo", "symptom"),
        ("dieta", "diet"),
        ("esercizio", "exercise"),
        ("stress", "stress"),
        ("riposo", "rest"),
        ("quartiere", "neighbourhood"),
        ("periferia", "suburbs"),
        ("centro", "centre"),
        ("traffico", "traffic"),
        ("inquinamento", "pollution"),
        ("rumore", "noise"),
        ("spazio", "space"),
        ("natura", "nature"),
        ("paesaggio", "landscape"),
        ("clima", "climate"),
        ("stagione", "season"),
        ("primavera", "spring"),
        ("estate", "summer"),
        ("autunno", "autumn"),
        ("inverno", "winter"),
        ("tuttavia", "however"),
        ("nonostante", "despite"),
        ("sebbene", "although"),
        ("benché", "even though"),
        ("affinché", "so that"),
        ("poiché", "since / because"),
        ("siccome", "since"),
        ("purché", "provided that"),
        ("qualora", "in the event that"),
        ("mentre", "whereas / while"),
        ("inoltre", "furthermore"),
        ("inoltre", "moreover"),
        ("inoltre", "besides"),
        ("inoltre", "also"),
        ("inoltre", "furthermore"),
        ("inoltre", "plus"),
        ("inoltre", "what's more"),
        ("inoltre", "additionally"),
        ("inoltre", "on top of that"),
        ("inoltre", "and also"),
        ("inoltre", "too"),
        ("inoltre", "as well"),
        ("oltre", "beyond / besides"),
        ("secondo", "according to"),
        ("riguardo", "regarding"),
        ("circa", "regarding / about"),
        ("verso", "towards"),
        ("contro", "against"),
        ("senza", "without"),
        ("tramite", "through / via"),
        ("mediante", "by means of"),
        ("grazie a", "thanks to"),
        ("a causa di", "because of"),
        ("soprattutto", "above all"),
        ("finalmente", "finally"),
        ("alla fine", "in the end"),
        ("all'inizio", "at the beginning"),
        ("nel frattempo", "in the meantime"),
        ("di solito", "usually"),
        ("spesso", "often"),
        ("raramente", "rarely"),
        ("occasionalmente", "occasionally"),
        ("recentemente", "recently"),
        ("attualmente", "currently"),
        ("probabilmente", "probably"),
        ("sicuramente", "surely"),
        ("ovviamente", "obviously"),
        ("purtroppo", "unfortunately"),
        ("fortunatamente", "fortunately"),
        ("sinceramente", "sincerely"),
        ("onestamente", "honestly"),
        ("praticamente", "practically"),
        ("relativamente", "relatively"),
        ("assolutamente", "absolutely"),
        ("completamente", "completely"),
        ("particolarmente", "particularly"),
        ("principalmente", "mainly"),
        ("generalmente", "generally"),
        ("effettivamente", "actually"),
        ("realmente", "really"),
        ("appena", "just / barely"),
        ("nemmeno", "not even"),
        ("neanche", "neither / not even"),
        ("neppure", "not even"),
        ("piuttosto", "rather"),
        ("abbastanza", "enough / quite"),
        ("sufficiente", "sufficient"),
        ("insufficiente", "insufficient"),
        ("evidente", "evident"),
        ("chiaro", "clear"),
        ("oscuro", "obscure / dark"),
        ("complesso", "complex"),
        ("semplice", "simple"),
        ("utile", "useful"),
        ("inutile", "useless"),
        ("efficace", "effective"),
        ("efficiente", "efficient"),
        ("pratico", "practical"),
        ("teorico", "theoretical"),
        ("reale", "real"),
        ("finto", "fake"),
        ("originale", "original"),
        ("comune", "common"),
        ("raro", "rare"),
        ("tipico", "typical"),
        ("adatto", "suitable"),
        ("inadatto", "unsuitable"),
        ("dipendente", "dependent / employee"),
        ("indipendente", "independent"),
        ("responsabile", "responsible"),
        ("consapevole", "aware"),
        ("inconsapevole", "unaware"),
    ],
)

add(
    "B2",
    [
        ("congiuntivo", "subjunctive"),
        ("ipotizzare", "to hypothesize"),
        ("sottolineare", "to emphasize"),
        ("evidenziare", "to highlight"),
        ("dimostrare", "to demonstrate"),
        ("comprovare", "to prove"),
        ("confutare", "to refute"),
        ("mettere in discussione", "to question"),
        ("prendere in considerazione", "to take into account"),
        ("tenere conto", "to take into account"),
        ("dare per scontato", "to take for granted"),
        ("rendersi conto", "to realize"),
        ("venire a conoscenza", "to come to know"),
        ("portare avanti", "to carry forward"),
        ("mettere in atto", "to implement"),
        ("entrare in vigore", "to come into force"),
        ("far fronte", "to face up to"),
        ("fare i conti", "to come to terms"),
        ("sottoporre", "to submit / subject"),
        ("sottostare", "to be subject to"),
        ("prevalere", "to prevail"),
        ("emergere", "to emerge"),
        ("sorgere", "to arise"),
        ("derivare", "to derive"),
        ("implicare", "to imply"),
        ("comportare", "to entail"),
        ("suscitare", "to arouse"),
        ("provocare", "to provoke"),
        ("generare", "to generate"),
        ("favorire", "to favour"),
        ("ostacolare", "to hinder"),
        ("compromesso", "compromise"),
        ("negoziazione", "negotiation"),
        ("dibattito", "debate"),
        ("tesi", "thesis"),
        ("ipotesi", "hypothesis"),
        ("teoria", "theory"),
        ("approccio", "approach"),
        ("metodo", "method"),
        ("criterio", "criterion"),
        ("parametro", "parameter"),
        ("fenomeno", "phenomenon"),
        ("processo", "process"),
        ("meccanismo", "mechanism"),
        ("struttura", "structure"),
        ("sistema", "system"),
        ("contesto", "context"),
        ("quadro", "framework / picture"),
        ("prospettiva", "perspective"),
        ("implicazione", "implication"),
        ("impatto", "impact"),
        ("portata", "scope"),
        ("entità", "entity / scale"),
        ("tendenza", "tendency"),
        ("evoluzione", "evolution"),
        ("trasformazione", "transformation"),
        ("innovazione", "innovation"),
        ("progresso", "progress"),
        ("crisi", "crisis"),
        ("conflitto", "conflict"),
        ("tensione", "tension"),
        ("equilibrio", "balance"),
        ("disuguaglianza", "inequality"),
        ("giustizia", "justice"),
        ("equità", "fairness"),
        ("etica", "ethics"),
        ("morale", "moral"),
        ("coscienza", "conscience"),
        ("libertà", "freedom"),
        ("uguaglianza", "equality"),
        ("solidarietà", "solidarity"),
        ("tolleranza", "tolerance"),
        ("pregiudizio", "prejudice"),
        ("stereotipo", "stereotype"),
        ("discriminazione", "discrimination"),
        ("integrazione", "integration"),
        ("migrazione", "migration"),
        ("cittadinanza", "citizenship"),
        ("diritto", "law / right"),
        ("legge", "law"),
        ("norma", "norm / regulation"),
        ("istituzione", "institution"),
        ("governo", "government"),
        ("parlamento", "parliament"),
        ("elezione", "election"),
        ("voto", "vote"),
        ("partito", "party (political)"),
        ("campagna", "campaign"),
        ("riforma", "reform"),
        ("politica", "politics / policy"),
        ("economia", "economy"),
        ("mercato", "market"),
        ("impresa", "company / enterprise"),
        ("azienda", "firm"),
        ("settore", "sector"),
        ("consumo", "consumption"),
        ("produzione", "production"),
        ("risorsa", "resource"),
        ("sostenibilità", "sustainability"),
        ("sviluppo", "development"),
        ("globalizzazione", "globalization"),
        ("tecnologia", "technology"),
        ("digitale", "digital"),
        ("intelligenza", "intelligence"),
        ("algoritmo", "algorithm"),
        ("privacy", "privacy"),
        ("dati", "data"),
        ("ricerca", "research"),
        ("scienza", "science"),
        ("evidenza", "evidence"),
        ("fonte", "source"),
        ("affidabile", "reliable"),
        ("plausibile", "plausible"),
        ("discutibile", "debatable"),
        ("controverso", "controversial"),
        ("rilevante", "relevant"),
        ("irrilevante", "irrelevant"),
        ("essenziale", "essential"),
        ("marginale", "marginal"),
        ("significativo", "significant"),
        ("trascurabile", "negligible"),
        ("inevitabile", "inevitable"),
        ("imprevedibile", "unpredictable"),
        ("sostenibile", "sustainable"),
        ("insostenibile", "unsustainable"),
        ("coerente", "coherent"),
        ("incoerente", "incoherent"),
        ("ambiguo", "ambiguous"),
        ("esplicito", "explicit"),
        ("implicito", "implicit"),
        ("oggettivo", "objective"),
        ("soggettivo", "subjective"),
        ("neutrale", "neutral"),
        ("parziale", "partial / biased"),
        ("approfondito", "in-depth"),
        ("superficiale", "superficial"),
        ("pertanto", "therefore"),
        ("dunque", "hence"),
        ("di conseguenza", "as a result"),
        ("in conclusione", "in conclusion"),
        ("in sintesi", "in short"),
        ("in altre parole", "in other words"),
        ("da un lato", "on the one hand"),
        ("dall'altro", "on the other hand"),
        ("a differenza di", "unlike"),
        ("al contrario", "on the contrary"),
        ("nondimeno", "nonetheless"),
        ("ciò nonostante", "nevertheless"),
        ("a patto che", "provided that"),
        ("nel caso in cui", "in the event that"),
        ("qualora", "should / if"),
        ("ove", "where / if (formal)"),
        ("onde", "in order to (formal)"),
        ("affinché", "in order that"),
        ("benché", "although"),
        ("sebbene", "although"),
        ("quantunque", "even though (literary)"),
        ("posto che", "given that"),
        ("ammesso che", "assuming that"),
        ("a condizione che", "on condition that"),
    ],
)


LEVEL_ORDER = {"A1": 0, "A2": 1, "B1": 2, "B2": 3}


def band_for_rank(rank: int) -> str:
    if rank < 500:
        return "A1"
    if rank < 1500:
        return "A2"
    if rank < 3000:
        return "B1"
    return "B2"


def main() -> None:
    lemma_rank: dict[str, int] = {}
    if FREQ_PATH.exists():
        with FREQ_PATH.open(encoding="utf-8") as f:
            for i, line in enumerate(f):
                if i >= 12000:
                    break
                word = line.split()[0].strip().lower() if line.split() else ""
                if word.isalpha() and word not in lemma_rank:
                    lemma_rank[word] = len(lemma_rank)

    vocab: dict[str, str] = {}
    for lemma, rank in lemma_rank.items():
        if rank < 5000:
            vocab[lemma] = band_for_rank(rank)

    for lemma, (level, _gloss) in PEDAGOGICAL.items():
        existing = vocab.get(lemma)
        if existing is None or LEVEL_ORDER[level] <= LEVEL_ORDER[existing]:
            vocab[lemma] = level

    gloss = {lemma: g for lemma, (_lvl, g) in PEDAGOGICAL.items()}

    VOCAB_OUT.parent.mkdir(parents=True, exist_ok=True)
    GLOSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    VOCAB_OUT.write_text(
        json.dumps(vocab, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    GLOSS_OUT.write_text(
        json.dumps(gloss, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    counts: dict[str, int] = defaultdict(int)
    for level in vocab.values():
        counts[level] += 1
    print(f"Wrote {len(vocab)} lemmas → {VOCAB_OUT}")
    print(f"Wrote {len(gloss)} glosses → {GLOSS_OUT}")
    print("Bands:", dict(counts))


if __name__ == "__main__":
    main()
