#!/usr/bin/env python3
"""Build CEFR-banded vocab + ru→en gloss JSON from a pedagogical core and frequency ranks."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FREQ_PATH = ROOT / "data" / "raw" / "ru_50k.txt"
VOCAB_OUT = ROOT / "data" / "vocab" / "ru_cefr.json"
GLOSS_OUT = ROOT / "data" / "gloss" / "ru_en.json"

# Pedagogical lemma → (CEFR, short English gloss). Overrides frequency banding.
# Levels are TORFL-inspired, not a licensed word list.
PEDAGOGICAL: dict[str, tuple[str, str]] = {}


def add(level: str, pairs: list[tuple[str, str]]) -> None:
    for lemma, gloss in pairs:
        lemma = lemma.strip().lower()
        if lemma and lemma not in PEDAGOGICAL:
            PEDAGOGICAL[lemma] = (level, gloss.strip())


add(
    "A1",
    [
        # pronouns / determiners
        ("я", "I"),
        ("ты", "you (informal)"),
        ("он", "he"),
        ("она", "she"),
        ("оно", "it"),
        ("мы", "we"),
        ("вы", "you (formal/plural)"),
        ("они", "they"),
        ("мой", "my"),
        ("твой", "your (informal)"),
        ("его", "his / him"),
        ("её", "her"),
        ("наш", "our"),
        ("ваш", "your (formal/plural)"),
        ("их", "their / them"),
        ("этот", "this"),
        ("тот", "that"),
        ("такой", "such / like this"),
        ("какой", "what / which"),
        ("кто", "who"),
        ("что", "what / that"),
        ("всё", "everything / all"),
        ("весь", "all / whole"),
        ("сам", "oneself / itself"),
        ("себя", "oneself"),
        ("свой", "one's own"),
        ("каждый", "each / every"),
        ("другой", "other / another"),
        ("один", "one / alone"),
        ("это", "this / it"),
        # function words
        ("и", "and"),
        ("а", "and / but"),
        ("но", "but"),
        ("или", "or"),
        ("не", "not"),
        ("ни", "neither / not a"),
        ("да", "yes"),
        ("нет", "no / there is not"),
        ("в", "in / into"),
        ("на", "on / onto"),
        ("с", "with / from"),
        ("у", "at / by (possession)"),
        ("к", "to / towards"),
        ("из", "from / out of"),
        ("за", "behind / for"),
        ("от", "from"),
        ("по", "along / according to"),
        ("для", "for"),
        ("до", "until / up to"),
        ("без", "without"),
        ("о", "about"),
        ("об", "about"),
        ("про", "about"),
        ("при", "at / by"),
        ("через", "through / in (time)"),
        ("после", "after"),
        ("между", "between"),
        ("вот", "here is"),
        ("даже", "even"),
        ("только", "only"),
        ("уже", "already"),
        ("ещё", "still / more"),
        ("тоже", "also"),
        ("очень", "very"),
        ("так", "so / like that"),
        ("там", "there"),
        ("тут", "here"),
        ("здесь", "here"),
        ("теперь", "now"),
        ("сейчас", "now"),
        ("потом", "then / later"),
        ("тогда", "then"),
        ("просто", "simply"),
        ("можно", "one may / it is possible"),
        ("надо", "it is necessary"),
        ("хорошо", "well / good"),
        ("плохо", "badly / bad"),
        ("много", "many / much"),
        ("мало", "few / little"),
        ("всегда", "always"),
        ("никогда", "never"),
        ("иногда", "sometimes"),
        ("сегодня", "today"),
        ("вчера", "yesterday"),
        ("завтра", "tomorrow"),
        ("быстро", "quickly"),
        ("медленно", "slowly"),
        ("рано", "early"),
        ("поздно", "late"),
        ("здесь", "here"),
        ("где", "where"),
        ("когда", "when"),
        ("почему", "why"),
        ("потому", "because"),
        ("как", "how / as"),
        ("сколько", "how many / how much"),
        ("ли", "whether (question particle)"),
        ("же", "emphasis particle"),
        ("ведь", "after all"),
        ("ну", "well / come on"),
        ("есть", "there is / to eat"),
        ("быть", "to be"),
        # numbers / time
        ("два", "two"),
        ("три", "three"),
        ("четыре", "four"),
        ("пять", "five"),
        ("шесть", "six"),
        ("семь", "seven"),
        ("восемь", "eight"),
        ("девять", "nine"),
        ("десять", "ten"),
        ("двадцать", "twenty"),
        ("тридцать", "thirty"),
        ("сорок", "forty"),
        ("пятьдесят", "fifty"),
        ("сто", "hundred"),
        ("тысяча", "thousand"),
        ("первый", "first"),
        ("второй", "second"),
        ("третий", "third"),
        ("час", "hour"),
        ("минута", "minute"),
        ("день", "day"),
        ("ночь", "night"),
        ("утро", "morning"),
        ("вечер", "evening"),
        ("неделя", "week"),
        ("месяц", "month"),
        ("год", "year"),
        ("понедельник", "Monday"),
        ("вторник", "Tuesday"),
        ("среда", "Wednesday"),
        ("четверг", "Thursday"),
        ("пятница", "Friday"),
        ("суббота", "Saturday"),
        ("воскресенье", "Sunday"),
        ("январь", "January"),
        ("февраль", "February"),
        ("март", "March"),
        ("апрель", "April"),
        ("май", "May"),
        ("июнь", "June"),
        ("июль", "July"),
        ("август", "August"),
        ("сентябрь", "September"),
        ("октябрь", "October"),
        ("ноябрь", "November"),
        ("декабрь", "December"),
        ("время", "time"),
        # people / family
        ("человек", "person"),
        ("мужчина", "man"),
        ("женщина", "woman"),
        ("ребёнок", "child"),
        ("дети", "children"),
        ("друг", "friend"),
        ("подруга", "female friend"),
        ("семья", "family"),
        ("мама", "mum"),
        ("папа", "dad"),
        ("отец", "father"),
        ("мать", "mother"),
        ("брат", "brother"),
        ("сестра", "sister"),
        ("сын", "son"),
        ("дочь", "daughter"),
        ("бабушка", "grandmother"),
        ("дедушка", "grandfather"),
        ("муж", "husband"),
        ("жена", "wife"),
        ("имя", "name"),
        ("фамилия", "surname"),
        ("студент", "student"),
        ("учитель", "teacher"),
        ("врач", "doctor"),
        ("водитель", "driver"),
        ("продавец", "salesperson"),
        ("официант", "waiter"),
        # home / city
        ("дом", "house / home"),
        ("квартира", "apartment"),
        ("комната", "room"),
        ("кухня", "kitchen"),
        ("ванная", "bathroom"),
        ("туалет", "toilet"),
        ("дверь", "door"),
        ("окно", "window"),
        ("стол", "table"),
        ("стул", "chair"),
        ("кровать", "bed"),
        ("шкаф", "wardrobe"),
        ("лампа", "lamp"),
        ("телефон", "telephone"),
        ("компьютер", "computer"),
        ("книга", "book"),
        ("тетрадь", "notebook"),
        ("ручка", "pen"),
        ("карандаш", "pencil"),
        ("школа", "school"),
        ("университет", "university"),
        ("работа", "work / job"),
        ("офис", "office"),
        ("магазин", "shop"),
        ("рынок", "market"),
        ("ресторан", "restaurant"),
        ("кафе", "café"),
        ("банк", "bank"),
        ("почта", "post office"),
        ("больница", "hospital"),
        ("аптека", "pharmacy"),
        ("вокзал", "station"),
        ("аэропорт", "airport"),
        ("отель", "hotel"),
        ("улица", "street"),
        ("площадь", "square"),
        ("парк", "park"),
        ("сад", "garden"),
        ("город", "city"),
        ("страна", "country"),
        ("столица", "capital"),
        ("Россия", "Russia"),
        ("Москва", "Moscow"),
        ("язык", "language / tongue"),
        ("урок", "lesson"),
        # food
        ("вода", "water"),
        ("хлеб", "bread"),
        ("молоко", "milk"),
        ("чай", "tea"),
        ("кофе", "coffee"),
        ("сок", "juice"),
        ("пиво", "beer"),
        ("вино", "wine"),
        ("мясо", "meat"),
        ("рыба", "fish"),
        ("курица", "chicken"),
        ("яйцо", "egg"),
        ("сыр", "cheese"),
        ("масло", "butter / oil"),
        ("сахар", "sugar"),
        ("соль", "salt"),
        ("суп", "soup"),
        ("салат", "salad"),
        ("рис", "rice"),
        ("картошка", "potato"),
        ("овощ", "vegetable"),
        ("фрукт", "fruit"),
        ("яблоко", "apple"),
        ("банан", "banana"),
        ("апельсин", "orange"),
        ("завтрак", "breakfast"),
        ("обед", "lunch"),
        ("ужин", "dinner"),
        # nature / world
        ("погода", "weather"),
        ("солнце", "sun"),
        ("дождь", "rain"),
        ("снег", "snow"),
        ("ветер", "wind"),
        ("небо", "sky"),
        ("земля", "earth / land"),
        ("море", "sea"),
        ("река", "river"),
        ("гора", "mountain"),
        ("дерево", "tree"),
        ("цветок", "flower"),
        ("собака", "dog"),
        ("кошка", "cat"),
        ("птица", "bird"),
        ("деньги", "money"),
        ("цена", "price"),
        ("билет", "ticket"),
        ("паспорт", "passport"),
        ("карта", "map / card"),
        ("фото", "photo"),
        ("письмо", "letter"),
        ("вопрос", "question"),
        ("ответ", "answer"),
        ("проблема", "problem"),
        ("жизнь", "life"),
        ("любовь", "love"),
        ("мир", "world / peace"),
        ("слово", "word"),
        ("место", "place"),
        ("сторона", "side"),
        ("конец", "end"),
        ("начало", "beginning"),
        ("путь", "way / path"),
        ("часть", "part"),
        ("дело", "matter / affair"),
        ("раз", "time / once"),
        ("рука", "hand / arm"),
        ("нога", "leg / foot"),
        ("голова", "head"),
        ("глаз", "eye"),
        ("лицо", "face"),
        ("тело", "body"),
        ("сердце", "heart"),
        # adjectives
        ("большой", "big"),
        ("маленький", "small"),
        ("новый", "new"),
        ("старый", "old"),
        ("молодой", "young"),
        ("хороший", "good"),
        ("плохой", "bad"),
        ("красивый", "beautiful"),
        ("интересный", "interesting"),
        ("трудный", "difficult"),
        ("лёгкий", "easy / light"),
        ("важный", "important"),
        ("нужный", "necessary"),
        ("свободный", "free"),
        ("счастливый", "happy"),
        ("грустный", "sad"),
        ("длинный", "long"),
        ("короткий", "short"),
        ("высокий", "tall / high"),
        ("низкий", "low / short"),
        ("белый", "white"),
        ("чёрный", "black"),
        ("красный", "red"),
        ("зелёный", "green"),
        ("синий", "blue"),
        ("жёлтый", "yellow"),
        ("тёплый", "warm"),
        ("холодный", "cold"),
        ("полный", "full"),
        ("пустой", "empty"),
        ("правый", "right"),
        ("левый", "left"),
        ("русский", "Russian"),
        ("английский", "English"),
        ("последний", "last"),
        ("следующий", "next"),
        ("главный", "main"),
        ("разный", "different"),
        ("сильный", "strong"),
        ("слабый", "weak"),
        ("богатый", "rich"),
        ("бедный", "poor"),
        # verbs (present-tense core)
        ("жить", "to live"),
        ("работать", "to work"),
        ("учиться", "to study"),
        ("читать", "to read"),
        ("писать", "to write"),
        ("говорить", "to speak"),
        ("сказать", "to say"),
        ("знать", "to know"),
        ("думать", "to think"),
        ("хотеть", "to want"),
        ("мочь", "to be able"),
        ("любить", "to love / like"),
        ("видеть", "to see"),
        ("смотреть", "to look / watch"),
        ("слушать", "to listen"),
        ("слышать", "to hear"),
        ("идти", "to go (on foot)"),
        ("ехать", "to go (by vehicle)"),
        ("делать", "to do / make"),
        ("давать", "to give"),
        ("брать", "to take"),
        ("покупать", "to buy"),
        ("продавать", "to sell"),
        ("открывать", "to open"),
        ("закрывать", "to close"),
        ("сидеть", "to sit"),
        ("стоять", "to stand"),
        ("лежать", "to lie"),
        ("спать", "to sleep"),
        ("пить", "to drink"),
        ("готовить", "to cook / prepare"),
        ("понимать", "to understand"),
        ("спрашивать", "to ask"),
        ("отвечать", "to answer"),
        ("звонить", "to call"),
        ("ждать", "to wait"),
        ("помогать", "to help"),
        ("играть", "to play"),
        ("петь", "to sing"),
        ("танцевать", "to dance"),
        ("рисовать", "to draw"),
        ("гулять", "to walk / stroll"),
        ("приходить", "to come / arrive"),
        ("уходить", "to leave"),
        ("начинать", "to begin"),
        ("кончать", "to finish"),
        ("нравиться", "to please / like"),
        ("звать", "to call / invite"),
        ("помнить", "to remember"),
        ("забывать", "to forget"),
        ("искать", "to look for"),
        ("находить", "to find"),
        ("показывать", "to show"),
        ("объяснять", "to explain"),
        ("изучать", "to study (a subject)"),
        ("отдыхать", "to rest"),
        ("плавать", "to swim"),
        ("бегать", "to run"),
        ("носить", "to wear / carry"),
        ("надевать", "to put on"),
        ("снимать", "to take off / film"),
        ("мыть", "to wash"),
        ("иметь", "to have"),
        ("стать", "to become"),
        ("дать", "to give (perfective)"),
        ("спросить", "to ask (perfective)"),
        ("понять", "to understand (perfective)"),
        ("должный", "must / ought to"),
        ("конечно", "of course"),
        ("спасибо", "thank you"),
        ("пожалуйста", "please / you're welcome"),
        ("здравствуйте", "hello (formal)"),
        ("привет", "hi"),
        ("пока", "bye"),
        ("извините", "excuse me / sorry"),
        ("давайте", "let's"),
    ],
)

add(
    "A2",
    [
        ("если", "if"),
        ("чтобы", "in order to / so that"),
        ("или", "or"),
        ("тоже", "also"),
        ("ещё", "still / yet / more"),
        ("уже", "already"),
        ("почти", "almost"),
        ("слишком", "too"),
        ("довольно", "rather / quite"),
        ("сразу", "immediately"),
        ("снова", "again"),
        ("обычно", "usually"),
        ("часто", "often"),
        ("редко", "rarely"),
        ("вместе", "together"),
        ("около", "near / about"),
        ("против", "against"),
        ("вместо", "instead of"),
        ("кроме", "except"),
        ("во время", "during"),
        ("перед", "in front of / before"),
        ("над", "above"),
        ("под", "under"),
        ("между", "between"),
        ("среди", "among"),
        ("вокруг", "around"),
        ("внутри", "inside"),
        ("снаружи", "outside"),
        ("сюда", "to here"),
        ("туда", "to there"),
        ("отсюда", "from here"),
        ("оттуда", "from there"),
        ("никто", "nobody"),
        ("ничто", "nothing"),
        ("кто-то", "someone"),
        ("что-то", "something"),
        ("какой-то", "some kind of"),
        ("несколько", "several"),
        ("оба", "both"),
        ("весь", "all"),
        ("самый", "the most / the very"),
        ("каждый", "every"),
        ("любой", "any"),
        ("собственный", "one's own"),
        # travel / daily
        ("поезд", "train"),
        ("автобус", "bus"),
        ("метро", "metro"),
        ("машина", "car"),
        ("такси", "taxi"),
        ("самолёт", "airplane"),
        ("велосипед", "bicycle"),
        ("остановка", "stop"),
        ("станция", "station"),
        ("дорога", "road"),
        ("светофор", "traffic light"),
        ("багаж", "luggage"),
        ("чемодан", "suitcase"),
        ("гостиница", "hotel"),
        ("номер", "number / hotel room"),
        ("ключ", "key"),
        ("регистрация", "check-in / registration"),
        ("экскурсия", "excursion"),
        ("музей", "museum"),
        ("театр", "theatre"),
        ("кино", "cinema"),
        ("концерт", "concert"),
        ("спорт", "sport"),
        ("футбол", "football"),
        ("пляж", "beach"),
        ("лес", "forest"),
        ("озеро", "lake"),
        ("остров", "island"),
        ("церковь", "church"),
        ("мост", "bridge"),
        ("центр", "centre"),
        ("район", "district"),
        ("адрес", "address"),
        ("этаж", "floor"),
        ("лифт", "lift"),
        ("вход", "entrance"),
        ("выход", "exit"),
        # shopping / money
        ("покупка", "purchase"),
        ("скидка", "discount"),
        ("дешёвый", "cheap"),
        ("дорогой", "expensive"),
        ("бесплатный", "free of charge"),
        ("счёт", "bill / account"),
        ("кассир", "cashier"),
        ("размер", "size"),
        ("цвет", "colour"),
        ("одежда", "clothes"),
        ("рубашка", "shirt"),
        ("платье", "dress"),
        ("брюки", "trousers"),
        ("юбка", "skirt"),
        ("пальто", "coat"),
        ("куртка", "jacket"),
        ("обувь", "shoes"),
        ("шапка", "hat"),
        ("сумка", "bag"),
        ("очки", "glasses"),
        ("подарок", "gift"),
        # health / body
        ("здоровье", "health"),
        ("болезнь", "illness"),
        ("температура", "temperature"),
        ("голова", "head"),
        ("зуб", "tooth"),
        ("горло", "throat"),
        ("живот", "stomach"),
        ("спина", "back"),
        ("боль", "pain"),
        ("лекарство", "medicine"),
        ("таблетка", "tablet"),
        ("рецепт", "prescription / recipe"),
        ("поликлиника", "clinic"),
        ("аптека", "pharmacy"),
        # work / study
        ("профессия", "profession"),
        ("должность", "position"),
        ("коллега", "colleague"),
        ("начальник", "boss"),
        ("зарплата", "salary"),
        ("встреча", "meeting"),
        ("проект", "project"),
        ("компьютер", "computer"),
        ("интернет", "internet"),
        ("почта", "mail"),
        ("сообщение", "message"),
        ("экзамен", "exam"),
        ("оценка", "grade / assessment"),
        ("домашнее задание", "homework"),
        ("курс", "course"),
        ("лекция", "lecture"),
        ("библиотека", "library"),
        ("словарь", "dictionary"),
        ("перевод", "translation"),
        ("ошибка", "mistake"),
        ("правило", "rule"),
        ("пример", "example"),
        ("тема", "topic"),
        ("текст", "text"),
        ("история", "story / history"),
        ("новость", "news"),
        ("газета", "newspaper"),
        ("журнал", "magazine"),
        ("телевидение", "television"),
        ("радио", "radio"),
        ("музыка", "music"),
        ("фильм", "film"),
        ("игра", "game"),
        ("праздник", "holiday"),
        ("день рождения", "birthday"),
        ("свадьба", "wedding"),
        ("гости", "guests"),
        ("приглашение", "invitation"),
        # adjectives A2
        ("удобный", "comfortable / convenient"),
        ("приятный", "pleasant"),
        ("опасный", "dangerous"),
        ("безопасный", "safe"),
        ("чистый", "clean"),
        ("грязный", "dirty"),
        ("тихий", "quiet"),
        ("шумный", "noisy"),
        ("занятый", "busy"),
        ("усталый", "tired"),
        ("голодный", "hungry"),
        ("больной", "ill"),
        ("здоровый", "healthy"),
        ("весёлый", "cheerful"),
        ("серьёзный", "serious"),
        ("странный", "strange"),
        ("обычный", "ordinary"),
        ("настоящий", "real"),
        ("возможный", "possible"),
        ("готовый", "ready"),
        ("похожий", "similar"),
        ("известный", "famous / known"),
        ("популярный", "popular"),
        ("современный", "modern"),
        ("традиционный", "traditional"),
        ("международный", "international"),
        ("местный", "local"),
        ("иностранный", "foreign"),
        ("открытый", "open"),
        ("закрытый", "closed"),
        ("правильный", "correct"),
        ("неправильный", "incorrect"),
        ("полезный", "useful"),
        ("вредный", "harmful"),
        ("сладкий", "sweet"),
        ("солёный", "salty"),
        ("острый", "spicy / sharp"),
        ("свежий", "fresh"),
        ("горячий", "hot"),
        ("тёмный", "dark"),
        ("светлый", "light"),
        ("широкий", "wide"),
        ("узкий", "narrow"),
        ("толстый", "thick / fat"),
        ("тонкий", "thin"),
        ("глубокий", "deep"),
        ("мелкий", "shallow / fine"),
        ("далёкий", "far"),
        ("близкий", "near / close"),
        ("будущий", "future"),
        ("прошлый", "past"),
        ("нынешний", "current"),
        # verbs A2 (past/future common)
        ("поехать", "to go (by vehicle, pf.)"),
        ("пойти", "to go (on foot, pf.)"),
        ("приехать", "to arrive (by vehicle)"),
        ("уехать", "to leave (by vehicle)"),
        ("прийти", "to come (on foot, pf.)"),
        ("уйти", "to leave (on foot, pf.)"),
        ("встать", "to get up"),
        ("лечь", "to lie down"),
        ("сесть", "to sit down"),
        ("купить", "to buy (pf.)"),
        ("продать", "to sell (pf.)"),
        ("открыть", "to open (pf.)"),
        ("закрыть", "to close (pf.)"),
        ("начать", "to begin (pf.)"),
        ("закончить", "to finish"),
        ("получить", "to receive"),
        ("отправить", "to send"),
        ("встретить", "to meet"),
        ("познакомиться", "to get acquainted"),
        ("рассказать", "to tell"),
        ("рассказывать", "to tell (impf.)"),
        ("объяснить", "to explain (pf.)"),
        ("повторить", "to repeat"),
        ("решить", "to decide / solve"),
        ("выбрать", "to choose"),
        ("попробовать", "to try"),
        ("использовать", "to use"),
        ("нуждаться", "to need"),
        ("бояться", "to be afraid"),
        ("радоваться", "to be glad"),
        ("интересоваться", "to be interested"),
        ("заниматься", "to be engaged in"),
        ("готовиться", "to prepare oneself"),
        ("одеваться", "to get dressed"),
        ("умываться", "to wash one's face"),
        ("чувствовать", "to feel"),
        ("казаться", "to seem"),
        ("случаться", "to happen"),
        ("происходить", "to take place"),
        ("продолжаться", "to continue"),
        ("закончиться", "to end"),
        ("получить", "to get"),
        ("потерять", "to lose"),
        ("найти", "to find (pf.)"),
        ("забыть", "to forget (pf.)"),
        ("вспомнить", "to recall"),
        ("пригласить", "to invite"),
        ("поблагодарить", "to thank"),
        ("извиниться", "to apologise"),
        ("соглашаться", "to agree"),
        ("отказываться", "to refuse"),
        ("советовать", "to advise"),
        ("предлагать", "to offer / suggest"),
        ("обещать", "to promise"),
        ("верить", "to believe"),
        ("надеяться", "to hope"),
        ("мечтать", "to dream"),
        ("планировать", "to plan"),
        ("путешествовать", "to travel"),
        ("переезжать", "to move (house)"),
        ("снимать квартиру", "to rent an apartment"),
        ("платить", "to pay"),
        ("стоить", "to cost"),
        ("весить", "to weigh"),
        ("измерять", "to measure"),
        ("сравнивать", "to compare"),
        ("менять", "to change"),
        ("улучшать", "to improve"),
        ("портить", "to spoil"),
        ("чинить", "to repair"),
        ("строить", "to build"),
        ("создавать", "to create"),
        ("развивать", "to develop"),
        ("учить", "to learn / teach"),
        ("преподавать", "to teach"),
        ("сдавать", "to take (an exam) / hand in"),
        ("получать", "to receive (impf.)"),
        ("переводить", "to translate / transfer"),
        ("печатать", "to type / print"),
        ("скачивать", "to download"),
        ("включать", "to switch on"),
        ("выключать", "to switch off"),
        ("заказывать", "to order"),
        ("бронировать", "to book"),
        ("регистрироваться", "to register"),
        ("проверить", "to check"),
        ("проверить", "to check"),
        ("успеть", "to manage in time"),
        ("опоздать", "to be late"),
        ("спешить", "to hurry"),
        ("остановиться", "to stop"),
        ("продолжить", "to continue (pf.)"),
        ("вернуться", "to return"),
        ("остаться", "to stay / remain"),
        ("провести", "to spend (time)"),
        ("прожить", "to live through"),
        ("родиться", "to be born"),
        ("умереть", "to die"),
        ("вырасти", "to grow up"),
        ("выйти замуж", "to get married (woman)"),
        ("жениться", "to get married (man)"),
        ("разводиться", "to get divorced"),
        ("война", "war"),
        ("смерть", "death"),
        ("сила", "strength / force"),
        ("правда", "truth"),
        ("закон", "law"),
        ("право", "right / law"),
        ("цель", "goal"),
        ("причина", "reason"),
        ("результат", "result"),
        ("опыт", "experience"),
        ("мнение", "opinion"),
        ("совет", "advice"),
        ("помощь", "help"),
        ("поддержка", "support"),
        ("отношение", "attitude / relationship"),
        ("чувство", "feeling"),
        ("настроение", "mood"),
        ("характер", "character"),
        ("привычка", "habit"),
        ("интерес", "interest"),
        ("хобби", "hobby"),
        ("успех", "success"),
        ("неудача", "failure"),
        ("шанс", "chance"),
        ("выбор", "choice"),
        ("решение", "decision"),
        ("изменение", "change"),
        ("развитие", "development"),
        ("будущее", "future"),
        ("прошлое", "past"),
        ("настоящее", "present"),
        ("общество", "society"),
        ("культура", "culture"),
        ("традиция", "tradition"),
        ("праздник", "celebration"),
        ("искусство", "art"),
        ("наука", "science"),
        ("техника", "technology"),
        ("природа", "nature"),
        ("окружающая среда", "environment"),
        ("животное", "animal"),
        ("растение", "plant"),
        ("воздух", "air"),
        ("огонь", "fire"),
        ("свет", "light"),
        ("луна", "moon"),
        ("звезда", "star"),
        ("озеро", "lake"),
        ("поле", "field"),
        ("деревня", "village"),
        ("регион", "region"),
        ("граница", "border"),
        ("правительство", "government"),
        ("президент", "president"),
        ("министр", "minister"),
        ("полиция", "police"),
        ("солдат", "soldier"),
        ("армия", "army"),
        ("преступление", "crime"),
        ("наказание", "punishment"),
        ("тюрьма", "prison"),
        ("суд", "court"),
        ("газета", "newspaper"),
        ("интервью", "interview"),
        ("реклама", "advertising"),
        ("компания", "company"),
        ("фирма", "firm"),
        ("завод", "factory"),
        ("продукт", "product"),
        ("услуга", "service"),
        ("клиент", "client"),
        ("качество", "quality"),
        ("количество", "quantity"),
        ("процент", "percent"),
        ("километр", "kilometre"),
        ("килограмм", "kilogram"),
        ("литр", "litre"),
        ("градус", "degree"),
        ("сезон", "season"),
        ("весна", "spring"),
        ("лето", "summer"),
        ("осень", "autumn"),
        ("зима", "winter"),
        ("север", "north"),
        ("юг", "south"),
        ("восток", "east"),
        ("запад", "west"),
    ],
)

add(
    "B1",
    [
        ("хотя", "although"),
        ("однако", "however"),
        ("поэтому", "therefore"),
        ("кроме того", "besides"),
        ("несмотря", "despite"),
        ("впрочем", "however"),
        ("зато", "on the other hand"),
        ("будто", "as if"),
        ("словно", "as though"),
        ("поскольку", "since / because"),
        ("следовательно", "consequently"),
        ("действительно", "indeed"),
        ("вероятно", "probably"),
        ("возможно", "possibly"),
        ("обязательно", "necessarily / definitely"),
        ("совершенно", "completely"),
        ("особенно", "especially"),
        ("именно", "exactly / namely"),
        ("наконец", "finally"),
        ("сначала", "at first"),
        ("затем", "then"),
        ("вдруг", "suddenly"),
        ("неожиданно", "unexpectedly"),
        ("постепенно", "gradually"),
        ("постоянно", "constantly"),
        ("временно", "temporarily"),
        ("заранее", "in advance"),
        ("вовремя", "on time"),
        ("навсегда", "forever"),
        ("вряд ли", "hardly / unlikely"),
        ("наоборот", "on the contrary"),
        ("кстати", "by the way"),
        ("например", "for example"),
        ("то есть", "that is"),
        ("другими словами", "in other words"),
        ("с одной стороны", "on the one hand"),
        ("с другой стороны", "on the other hand"),
        ("во-первых", "firstly"),
        ("во-вторых", "secondly"),
        ("итак", "so / thus"),
        ("значит", "that means"),
        ("кажется", "it seems"),
        ("оказывается", "it turns out"),
        ("нужно", "it is necessary"),
        ("нельзя", "one must not"),
        ("стоит", "it is worth"),
        ("следует", "one should"),
        ("удаться", "to succeed"),
        ("приходиться", "to have to"),
        ("являться", "to be / constitute"),
        ("составлять", "to make up / compose"),
        ("представлять", "to represent / introduce"),
        ("относиться", "to relate / treat"),
        ("зависеть", "to depend"),
        ("влиять", "to influence"),
        ("требовать", "to demand"),
        ("позволять", "to allow"),
        ("запрещать", "to forbid"),
        ("разрешать", "to permit"),
        ("избегать", "to avoid"),
        ("справляться", "to cope"),
        ("удаваться", "to manage"),
        ("стремиться", "to strive"),
        ("достигать", "to achieve"),
        ("преодолевать", "to overcome"),
        ("терпеть", "to endure"),
        ("страдать", "to suffer"),
        ("жаловаться", "to complain"),
        ("критиковать", "to criticise"),
        ("оценивать", "to evaluate"),
        ("анализировать", "to analyse"),
        ("обсуждать", "to discuss"),
        ("спорить", "to argue"),
        ("убеждать", "to convince"),
        ("доказывать", "to prove"),
        ("отрицать", "to deny"),
        ("подтверждать", "to confirm"),
        ("сомневаться", "to doubt"),
        ("предполагать", "to assume"),
        ("ожидать", "to expect"),
        ("предсказывать", "to predict"),
        ("замечать", "to notice"),
        ("обращать внимание", "to pay attention"),
        ("учитывать", "to take into account"),
        ("включать", "to include / switch on"),
        ("содержать", "to contain"),
        ("состоять", "to consist"),
        ("отличаться", "to differ"),
        ("сравнивать", "to compare"),
        ("соединять", "to connect"),
        ("разделять", "to divide / share"),
        ("увеличивать", "to increase"),
        ("уменьшать", "to decrease"),
        ("расширять", "to expand"),
        ("сокращать", "to reduce"),
        ("заменять", "to replace"),
        ("сохранять", "to preserve"),
        ("разрушать", "to destroy"),
        ("восстанавливать", "to restore"),
        ("производить", "to produce"),
        ("потреблять", "to consume"),
        ("экономить", "to save (money/resources)"),
        ("тратить", "to spend"),
        ("зарабатывать", "to earn"),
        ("вкладывать", "to invest"),
        ("занимать", "to occupy / borrow"),
        ("сдавать в аренду", "to rent out"),
        ("переводить", "to translate"),
        ("выражать", "to express"),
        ("описывать", "to describe"),
        ("изображать", "to depict"),
        ("отражать", "to reflect"),
        ("скрывать", "to hide"),
        ("обнаруживать", "to discover"),
        ("исследовать", "to research"),
        ("изучать", "to study"),
        ("осваивать", "to master"),
        ("применять", "to apply"),
        ("внедрять", "to implement"),
        ("организовывать", "to organise"),
        ("управлять", "to manage"),
        ("руководить", "to lead"),
        ("подчиняться", "to obey"),
        ("сотрудничать", "to cooperate"),
        ("конкурировать", "to compete"),
        ("побеждать", "to win"),
        ("проигрывать", "to lose (a contest)"),
        ("участвовать", "to participate"),
        ("присоединяться", "to join"),
        ("отказываться", "to refuse"),
        ("соглашаться", "to agree"),
        ("идти", "to go (on foot, unidirectional)"),
        ("ходить", "to go (on foot, multidirectional)"),
        ("ехать", "to go (vehicle, unidirectional)"),
        ("ездить", "to go (vehicle, multidirectional)"),
        ("лететь", "to fly (unidirectional)"),
        ("летать", "to fly (multidirectional)"),
        ("плыть", "to swim / sail (uni.)"),
        ("плавать", "to swim (multi.)"),
        ("нести", "to carry (uni.)"),
        ("носить", "to carry / wear (multi.)"),
        ("вести", "to lead / drive (uni.)"),
        ("водить", "to lead / drive (multi.)"),
        ("везти", "to convey (uni.)"),
        ("возить", "to convey (multi.)"),
        ("бежать", "to run (uni.)"),
        ("бегать", "to run (multi.)"),
        # nouns B1
        ("государство", "state"),
        ("власть", "power / authority"),
        ("гражданин", "citizen"),
        ("население", "population"),
        ("нация", "nation"),
        ("народ", "people / nation"),
        ("поколение", "generation"),
        ("молодёжь", "youth"),
        ("пенсионер", "pensioner"),
        ("безработица", "unemployment"),
        ("образование", "education"),
        ("воспитание", "upbringing"),
        ("университет", "university"),
        ("исследование", "research"),
        ("открытие", "discovery"),
        ("изобретение", "invention"),
        ("технология", "technology"),
        ("информация", "information"),
        ("данные", "data"),
        ("факт", "fact"),
        ("доказательство", "proof"),
        ("аргумент", "argument"),
        ("вывод", "conclusion"),
        ("гипотеза", "hypothesis"),
        ("теория", "theory"),
        ("метод", "method"),
        ("способ", "way / method"),
        ("средство", "means"),
        ("условие", "condition"),
        ("требование", "requirement"),
        ("обязанность", "duty"),
        ("ответственность", "responsibility"),
        ("свобода", "freedom"),
        ("равенство", "equality"),
        ("справедливость", "justice"),
        ("честность", "honesty"),
        ("уважение", "respect"),
        ("доверие", "trust"),
        ("дружба", "friendship"),
        ("конфликт", "conflict"),
        ("согласие", "agreement"),
        ("компромисс", "compromise"),
        ("переговоры", "negotiations"),
        ("договор", "treaty / contract"),
        ("соглашение", "agreement"),
        ("закон", "law"),
        ("право", "right"),
        ("обязанность", "obligation"),
        ("налог", "tax"),
        ("бюджет", "budget"),
        ("кризис", "crisis"),
        ("инфляция", "inflation"),
        ("рынок", "market"),
        ("спрос", "demand"),
        ("предложение", "supply / offer"),
        ("конкуренция", "competition"),
        ("прибыль", "profit"),
        ("убыток", "loss"),
        ("инвестиция", "investment"),
        ("кредит", "loan / credit"),
        ("долг", "debt / duty"),
        ("собственность", "property"),
        ("имущество", "possessions"),
        ("жильё", "housing"),
        ("аренда", "rent"),
        ("ипотека", "mortgage"),
        ("транспорт", "transport"),
        ("сообщение", "communication / message"),
        ("связь", "connection / communications"),
        ("энергия", "energy"),
        ("ресурс", "resource"),
        ("сырьё", "raw material"),
        ("промышленность", "industry"),
        ("сельское хозяйство", "agriculture"),
        ("торговля", "trade"),
        ("туризм", "tourism"),
        ("экология", "ecology"),
        ("загрязнение", "pollution"),
        ("изменение климата", "climate change"),
        ("катастрофа", "disaster"),
        ("авария", "accident"),
        ("риск", "risk"),
        ("угроза", "threat"),
        ("защита", "protection"),
        ("безопасность", "security / safety"),
        ("здоровье", "health"),
        ("лечение", "treatment"),
        ("операция", "operation"),
        ("диета", "diet"),
        ("привычка", "habit"),
        ("зависимость", "addiction / dependence"),
        ("стресс", "stress"),
        ("эмоция", "emotion"),
        ("память", "memory"),
        ("воображение", "imagination"),
        ("творчество", "creativity"),
        ("талант", "talent"),
        ("способность", "ability"),
        ("навык", "skill"),
        ("знание", "knowledge"),
        ("умение", "ability / know-how"),
        ("опыт", "experience"),
        ("карьера", "career"),
        ("достижение", "achievement"),
        ("недостаток", "shortcoming / shortage"),
        ("преимущество", "advantage"),
        ("недостаток", "disadvantage"),
        ("особенность", "peculiarity"),
        ("различие", "difference"),
        ("сходство", "similarity"),
        ("влияние", "influence"),
        ("значение", "meaning / significance"),
        ("цель", "aim"),
        ("задача", "task"),
        ("проблема", "problem"),
        ("решение", "solution"),
        ("ситуация", "situation"),
        ("обстоятельство", "circumstance"),
        ("событие", "event"),
        ("процесс", "process"),
        ("этап", "stage"),
        ("период", "period"),
        ("срок", "deadline / term"),
        ("момент", "moment"),
        ("возможность", "opportunity / possibility"),
        ("необходимость", "necessity"),
        ("потребность", "need"),
        ("желание", "desire"),
        ("намерение", "intention"),
        ("попытка", "attempt"),
        ("успех", "success"),
        ("прогресс", "progress"),
        ("реформа", "reform"),
        ("политика", "politics / policy"),
        ("экономика", "economy"),
        ("общество", "society"),
        # adjectives B1
        ("значительный", "significant"),
        ("существенный", "essential"),
        ("основной", "basic / main"),
        ("важнейший", "most important"),
        ("типичный", "typical"),
        ("характерный", "characteristic"),
        ("очевидный", "obvious"),
        ("ясный", "clear"),
        ("сложный", "complex"),
        ("простой", "simple"),
        ("эффективный", "effective"),
        ("полезный", "useful"),
        ("вредный", "harmful"),
        ("опасный", "dangerous"),
        ("надёжный", "reliable"),
        ("уверенный", "confident"),
        ("спокойный", "calm"),
        ("нервный", "nervous"),
        ("эмоциональный", "emotional"),
        ("логичный", "logical"),
        ("разумный", "reasonable"),
        ("честный", "honest"),
        ("справедливый", "fair"),
        ("жестокий", "cruel"),
        ("добрый", "kind"),
        ("вежливый", "polite"),
        ("грубый", "rude"),
        ("скромный", "modest"),
        ("гордый", "proud"),
        ("ленивый", "lazy"),
        ("трудолюбивый", "hard-working"),
        ("ответственный", "responsible"),
        ("самостоятельный", "independent"),
        ("зависимый", "dependent"),
        ("активный", "active"),
        ("пассивный", "passive"),
        ("творческий", "creative"),
        ("практический", "practical"),
        ("теоретический", "theoretical"),
        ("официальный", "official"),
        ("неофициальный", "unofficial"),
        ("личный", "personal"),
        ("общественный", "public / social"),
        ("политический", "political"),
        ("экономический", "economic"),
        ("социальный", "social"),
        ("культурный", "cultural"),
        ("исторический", "historical"),
        ("научный", "scientific"),
        ("технический", "technical"),
        ("цифровой", "digital"),
        ("глобальный", "global"),
        ("местный", "local"),
        ("временный", "temporary"),
        ("постоянный", "permanent"),
        ("ежедневный", "daily"),
        ("ежегодный", "annual"),
        ("предыдущий", "previous"),
        ("последующий", "subsequent"),
        ("нынешний", "current"),
        ("древний", "ancient"),
        ("современный", "contemporary"),
        ("традиционный", "traditional"),
        ("инновационный", "innovative"),
        ("экологический", "ecological"),
        ("устойчивый", "sustainable / stable"),
        ("гибкий", "flexible"),
        ("жёсткий", "strict / rigid"),
        ("мягкий", "soft / mild"),
        ("резкий", "sharp / abrupt"),
        ("плавный", "smooth"),
        ("равномерный", "even / uniform"),
        ("неравномерный", "uneven"),
        ("достаточный", "sufficient"),
        ("недостаточный", "insufficient"),
        ("избыточный", "excessive"),
        ("ограниченный", "limited"),
        ("безграничный", "boundless"),
        ("общий", "common / general"),
        ("частный", "private / particular"),
        ("конкретный", "concrete / specific"),
        ("абстрактный", "abstract"),
        ("положительный", "positive"),
        ("отрицательный", "negative"),
        ("нейтральный", "neutral"),
        ("противоположный", "opposite"),
        ("взаимный", "mutual"),
        ("односторонний", "one-sided"),
        ("двусторонний", "bilateral"),
        ("внутренний", "internal"),
        ("внешний", "external"),
        ("начальный", "initial"),
        ("конечный", "final"),
        ("промежуточный", "intermediate"),
        ("максимальный", "maximum"),
        ("минимальный", "minimum"),
        ("средний", "average / middle"),
        ("высший", "highest"),
        ("низший", "lowest"),
    ],
)

add(
    "B2",
    [
        ("тем не менее", "nevertheless"),
        ("вместе с тем", "at the same time"),
        ("в то время как", "whereas"),
        ("при условии", "provided that"),
        ("в случае", "in the event of"),
        ("с целью", "with the aim of"),
        ("в связи", "in connection with"),
        ("по мере", "as / in proportion as"),
        ("в отличие", "unlike / in contrast"),
        ("наряду", "alongside"),
        ("посредством", "by means of"),
        ("в рамках", "within the framework of"),
        ("с точки зрения", "from the point of view of"),
        ("в значительной степени", "to a considerable extent"),
        ("так называемый", "so-called"),
        ("данный", "the given / this"),
        ("указанный", "the specified"),
        ("соответствующий", "corresponding"),
        ("вышеупомянутый", "aforementioned"),
        ("нижеследующий", "the following"),
        ("подлежащий", "subject to"),
        ("касающийся", "concerning"),
        ("обусловленный", "conditioned / due to"),
        ("вызванный", "caused"),
        ("связанный", "connected"),
        ("основанный", "based"),
        ("направленный", "directed"),
        ("предназначенный", "intended"),
        ("осуществлять", "to carry out"),
        ("обеспечивать", "to ensure / provide"),
        ("предусматривать", "to provide for"),
        ("способствовать", "to promote / contribute"),
        ("препятствовать", "to hinder"),
        ("подразумевать", "to imply"),
        ("свидетельствовать", "to testify / indicate"),
        ("указывать", "to indicate"),
        ("характеризовать", "to characterise"),
        ("классифицировать", "to classify"),
        ("формулировать", "to formulate"),
        ("обосновывать", "to substantiate"),
        ("опровергать", "to refute"),
        ("интерпретировать", "to interpret"),
        ("обобщать", "to generalise"),
        ("конкретизировать", "to specify"),
        ("уточнять", "to clarify"),
        ("корректировать", "to correct"),
        ("регламентировать", "to regulate"),
        ("нормировать", "to standardise"),
        ("стимулировать", "to stimulate"),
        ("мотивировать", "to motivate"),
        ("инициировать", "to initiate"),
        ("реализовывать", "to implement"),
        ("интегрировать", "to integrate"),
        ("оптимизировать", "to optimise"),
        ("модернизировать", "to modernise"),
        ("диверсифицировать", "to diversify"),
        ("консолидировать", "to consolidate"),
        ("мобилизовать", "to mobilise"),
        ("нейтрализовать", "to neutralise"),
        ("компенсировать", "to compensate"),
        ("балансировать", "to balance"),
        ("прогнозировать", "to forecast"),
        ("моделировать", "to model"),
        ("структурировать", "to structure"),
        ("систематизировать", "to systematise"),
        ("парадигма", "paradigm"),
        ("концепция", "concept"),
        ("подход", "approach"),
        ("принцип", "principle"),
        ("критерий", "criterion"),
        ("параметр", "parameter"),
        ("показатель", "indicator"),
        ("тенденция", "trend"),
        ("динамика", "dynamics"),
        ("структура", "structure"),
        ("система", "system"),
        ("механизм", "mechanism"),
        ("функция", "function"),
        ("роль", "role"),
        ("статус", "status"),
        ("иерархия", "hierarchy"),
        ("институт", "institution"),
        ("инфраструктура", "infrastructure"),
        ("стратегия", "strategy"),
        ("тактика", "tactics"),
        ("приоритет", "priority"),
        ("инициатива", "initiative"),
        ("кампания", "campaign"),
        ("программа", "programme"),
        ("проект", "project"),
        ("реализация", "implementation"),
        ("эффективность", "efficiency"),
        ("производительность", "productivity"),
        ("конкурентоспособность", "competitiveness"),
        ("устойчивость", "stability / sustainability"),
        ("прозрачность", "transparency"),
        ("подотчётность", "accountability"),
        ("коррупция", "corruption"),
        ("бюрократия", "bureaucracy"),
        ("реформа", "reform"),
        ("модернизация", "modernisation"),
        ("глобализация", "globalisation"),
        ("урбанизация", "urbanisation"),
        ("миграция", "migration"),
        ("демография", "demography"),
        ("идентичность", "identity"),
        ("менталитет", "mentality"),
        ("стереотип", "stereotype"),
        ("предрассудок", "prejudice"),
        ("толерантность", "tolerance"),
        ("дискриминация", "discrimination"),
        ("интеграция", "integration"),
        ("сегрегация", "segregation"),
        ("ассоциация", "association"),
        ("федерация", "federation"),
        ("автономия", "autonomy"),
        ("суверенитет", "sovereignty"),
        ("юрисдикция", "jurisdiction"),
        ("законодательство", "legislation"),
        ("норматив", "standard / norm"),
        ("постановление", "decree / resolution"),
        ("директива", "directive"),
        ("резолюция", "resolution"),
        ("санкция", "sanction"),
        ("эмбарго", "embargo"),
        ("дипломатия", "diplomacy"),
        ("альянс", "alliance"),
        ("коалиция", "coalition"),
        ("конфронтация", "confrontation"),
        ("эскалация", "escalation"),
        ("деэскалация", "de-escalation"),
        ("стабильность", "stability"),
        ("нестабильность", "instability"),
        ("неопределённость", "uncertainty"),
        ("перспектива", "prospect"),
        ("последствие", "consequence"),
        ("предпосылка", "prerequisite"),
        ("закономерность", "regularity / pattern"),
        ("исключение", "exception"),
        ("противоречие", "contradiction"),
        ("парадокс", "paradox"),
        ("дилемма", "dilemma"),
        ("альтернатива", "alternative"),
        ("компромисс", "compromise"),
        ("консенсус", "consensus"),
        ("полемика", "polemic"),
        ("дискуссия", "discussion"),
        ("дебаты", "debate"),
        ("риторика", "rhetoric"),
        ("нарратив", "narrative"),
        ("дискурс", "discourse"),
        ("контекст", "context"),
        ("подтекст", "subtext"),
        ("импликация", "implication"),
        ("аллюзия", "allusion"),
        ("метафора", "metaphor"),
        ("символ", "symbol"),
        ("образ", "image / character"),
        ("жанр", "genre"),
        ("стиль", "style"),
        ("эстетика", "aesthetics"),
        ("этика", "ethics"),
        ("философия", "philosophy"),
        ("идеология", "ideology"),
        ("мировоззрение", "worldview"),
        ("ценность", "value"),
        ("норма", "norm"),
        ("мораль", "morals"),
        ("совесть", "conscience"),
        ("достоинство", "dignity"),
        ("честь", "honour"),
        ("репутация", "reputation"),
        ("авторитет", "authority"),
        ("престиж", "prestige"),
        ("влияние", "influence"),
        ("господство", "dominance"),
        ("подчинение", "subordination"),
        ("сопротивление", "resistance"),
        ("протест", "protest"),
        ("восстание", "uprising"),
        ("революция", "revolution"),
        ("эволюция", "evolution"),
        ("трансформация", "transformation"),
        ("адаптация", "adaptation"),
        ("инновация", "innovation"),
        ("эксперимент", "experiment"),
        ("наблюдение", "observation"),
        ("измерение", "measurement"),
        ("статистика", "statistics"),
        ("выборка", "sample"),
        ("корреляция", "correlation"),
        ("каузальность", "causality"),
        ("вероятность", "probability"),
        ("достоверность", "reliability"),
        ("валидность", "validity"),
        ("объективность", "objectivity"),
        ("субъективность", "subjectivity"),
        ("предвзятость", "bias"),
        ("скептицизм", "scepticism"),
        ("эмпирика", "empirics"),
        ("дедукция", "deduction"),
        ("индукция", "induction"),
        ("синтез", "synthesis"),
        ("анализ", "analysis"),
        ("критика", "criticism"),
        ("рецензия", "review"),
        ("публикация", "publication"),
        ("цитата", "quotation"),
        ("ссылка", "reference"),
        ("источник", "source"),
        ("первоисточник", "primary source"),
        ("архив", "archive"),
        ("свидетельство", "testimony / certificate"),
        ("мемуары", "memoirs"),
        ("хроника", "chronicle"),
        ("эпоха", "epoch"),
        ("эра", "era"),
        ("столетие", "century"),
        ("десятилетие", "decade"),
        ("наследие", "heritage"),
        ("преемственность", "continuity"),
        ("разрыв", "rupture / gap"),
        ("преемник", "successor"),
        ("предшественник", "predecessor"),
        ("современник", "contemporary (person)"),
        ("поколение", "generation"),
        ("наследие", "legacy"),
        ("который", "which / who (relative)"),
    ],
)


LEVEL_ORDER = {"A1": 0, "A2": 1, "B1": 2, "B2": 3}


def lemma_of(morph, word: str) -> str | None:
    parsed = morph.parse(word)
    if not parsed:
        return None
    p = parsed[0]
    if p.tag.POS in {"PNCT", None} and not word.isalpha():
        return None
    lemma = (p.normal_form or word).lower()
    if not lemma.isalpha() and "-" not in lemma:
        return None
    # skip obvious latin leftovers from subtitles
    if all(ord(c) < 128 for c in lemma):
        return None
    return lemma


def band_for_rank(rank: int) -> str:
    if rank < 500:
        return "A1"
    if rank < 1500:
        return "A2"
    if rank < 3000:
        return "B1"
    return "B2"


def main() -> None:
    import pymorphy3

    morph = pymorphy3.MorphAnalyzer()
    lemma_rank: dict[str, int] = {}

    if FREQ_PATH.exists():
        with FREQ_PATH.open(encoding="utf-8") as f:
            for i, line in enumerate(f):
                if i >= 12000:
                    break
                parts = line.split()
                if not parts:
                    continue
                form = parts[0]
                lemma = lemma_of(morph, form)
                if lemma and lemma not in lemma_rank:
                    lemma_rank[lemma] = len(lemma_rank)

    vocab: dict[str, str] = {}
    for lemma, rank in lemma_rank.items():
        if rank < 5000:
            vocab[lemma] = band_for_rank(rank)

    # Pedagogical overlay wins (and may add lemmas missing from frequency).
    for lemma, (level, _gloss) in PEDAGOGICAL.items():
        existing = vocab.get(lemma)
        if existing is None or LEVEL_ORDER[level] <= LEVEL_ORDER[existing]:
            vocab[lemma] = level

    gloss = {lemma: g for lemma, (_lvl, g) in PEDAGOGICAL.items()}

    VOCAB_OUT.parent.mkdir(parents=True, exist_ok=True)
    GLOSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    VOCAB_OUT.write_text(
        json.dumps(vocab, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    GLOSS_OUT.write_text(
        json.dumps(gloss, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    counts: dict[str, int] = defaultdict(int)
    for level in vocab.values():
        counts[level] += 1
    print(f"Wrote {len(vocab)} lemmas → {VOCAB_OUT}")
    print(f"Wrote {len(gloss)} glosses → {GLOSS_OUT}")
    print("Bands:", dict(counts))


if __name__ == "__main__":
    main()
