import {
  DEMO,
  DHB,
  KTB,
  POLITE_PAST,
  POLITE_PRES,
  QR,
  SHR,
  TE_IRU,
  ar,
  it,
  ja,
  punct,
  ru,
} from "@/components/landing/demo-data";
import { isContentWord, type Calibration, type CefrLevel, type LangCode, type Passage, type Token } from "@/lib/types";

const BYT = {
  letters: "ب ي ت",
  pattern: "فَعَلَ",
  form: "I",
  form_name: "فَعَلَ",
  meaning: "spend the night; house",
};

const QRA = QR;

const KWN = {
  letters: "ك و ن",
  pattern: "فَعَلَ",
  form: "I",
  form_name: "فَعَلَ",
  meaning: "be",
};

const SHRB = {
  letters: "ش ر ب",
  pattern: "فَعَلَ",
  form: "I",
  form_name: "فَعَلَ",
  meaning: "drink",
};

const NZL = {
  letters: "ن ظ ر",
  pattern: "فَعَلَ",
  form: "I",
  form_name: "فَعَلَ",
  meaning: "wait; look",
};

function tokensToText(tokens: Token[], language: LangCode): string {
  return tokens.map((t) => t.text + (t.ws ?? "")).join(language === "ja" ? "" : "").replace(/\s+$/, "");
}

function sampleLemmas(tokens: Token[], language: LangCode): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const tok of tokens) {
    if (!tok.lemma || !isContentWord(tok, language) || seen.has(tok.lemma)) continue;
    seen.add(tok.lemma);
    out.push(tok.lemma);
    if (out.length >= 8) break;
  }
  return out;
}

const PASSPORT: Record<LangCode, Record<CefrLevel, { allowed: string[]; banned: string[] }>> = {
  ja: {
    A1: {
      allowed: ["です/ます polite style", "core particles は が を に の"],
      banned: ["て-form", "plain past た", "plain negative ない", "ている aspect", "conditionals ば/たら/なら", "potential", "causative", "passive", "relative clauses", "keigo"],
    },
    A2: {
      allowed: ["て-form", "plain past た", "plain negative ない"],
      banned: ["ている aspect", "conditionals ば/たら/なら", "potential", "causative", "passive", "relative clauses", "keigo"],
    },
    B1: {
      allowed: ["て-form", "plain past た", "ている aspect", "conditionals ば/たら/なら", "potential", "causative", "relative clauses"],
      banned: ["passive", "keigo"],
    },
    B2: { allowed: ["passive", "keigo"], banned: [] },
  },
  ru: {
    A1: { allowed: ["nominative"], banned: ["PRTF", "PRTS", "GRND", "COMP"] },
    A2: { allowed: ["nominative", "accusative", "genitive", "prepositional", "dative"], banned: ["PRTF", "PRTS", "GRND", "COMP"] },
    B1: { allowed: ["nominative", "accusative", "genitive", "prepositional", "dative", "instrumental"], banned: ["PRTF", "PRTS", "GRND"] },
    B2: { allowed: ["nominative", "accusative", "genitive", "prepositional", "dative", "instrumental"], banned: [] },
  },
  it: {
    A1: { allowed: ["present indicative"], banned: ["passato prossimo", "imperfetto", "futuro", "condizionale", "congiuntivo", "gerundio", "relative che"] },
    A2: { allowed: ["present indicative", "passato prossimo"], banned: ["imperfetto", "futuro", "condizionale", "congiuntivo", "gerundio", "relative che"] },
    B1: { allowed: ["present indicative", "passato prossimo", "imperfetto", "futuro"], banned: ["congiuntivo", "gerundio", "passato remoto"] },
    B2: { allowed: ["congiuntivo", "gerundio"], banned: [] },
  },
  ar: {
    A1: { allowed: ["present Form I", "nominal sentences"], banned: ["past (الماضي)", "future سـ/سوف", "إنّ / أنّ", "relative الذي", "Form II", "Form VIII"] },
    A2: { allowed: ["present Form I", "past (الماضي)"], banned: ["إنّ / أنّ", "relative الذي", "jussive لم", "Form II"] },
    B1: { allowed: ["past (الماضي)", "عندما", "كان + verb"], banned: ["إنّ / أنّ", "passive", "Form II"] },
    B2: { allowed: ["إنّ / أنّ", "passive"], banned: [] },
  },
};

function calibration(language: LangCode, level: CefrLevel, tokens: Token[]): Calibration {
  const passport = PASSPORT[language][level];
  return {
    passed: true,
    attempts: 1,
    overlevel_lemma_rate: 0.03,
    subordinate_rate: level === "A1" ? 0 : level === "A2" ? 0.04 : 0.12,
    forbidden_case_rate: 0,
    forbidden_tense_rate: 0,
    forbidden_pos_rate: 0,
    flags: [],
    warnings: [],
    allowed_constructions: passport.allowed,
    banned_constructions: passport.banned,
    forbidden_used: [],
    sample_lemmas: sampleLemmas(tokens, language),
  };
}

function makePassage(opts: {
  id: string;
  language: LangCode;
  level: CefrLevel;
  topic: string;
  genre: string;
  title: string;
  tokens: Token[];
  translation: string;
  created_at: string;
  comprehension?: Passage["comprehension"];
  source_name?: string;
  source_url?: string | null;
  source_date?: string;
}): Passage {
  return {
    id: opts.id,
    language: opts.language,
    level: opts.level,
    topic: opts.topic,
    genre: opts.genre,
    title: opts.title,
    text: tokensToText(opts.tokens, opts.language),
    tokens: opts.tokens,
    calibration: calibration(opts.language, opts.level, opts.tokens),
    word_count: opts.tokens.filter((t) => t.is_word).length,
    created_at: opts.created_at,
    translation: opts.translation,
    comprehension: opts.comprehension,
    source_name: opts.source_name,
    source_url: opts.source_url,
    source_date: opts.source_date,
  };
}

function fromDemo(
  id: string,
  lang: LangCode,
  translation: string,
  created_at: string,
): Passage {
  const demo = DEMO[lang];
  return makePassage({
    id,
    language: lang,
    level: demo.level,
    topic: demo.topic,
    genre: "daily_life",
    title: demo.title,
    tokens: demo.tokens,
    translation,
    created_at,
  });
}

const JA_ASA: Token[] = [
  ja("私", { pos: "pronoun", reading: "わたし", gloss: "I; me", kanji: [["私", "わたし"]] }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("学生", { pos: "noun", reading: "がくせい", gloss: "student", kanji: [["学", "がく"], ["生", "せい"]] }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
  ja("今日", { pos: "noun", reading: "きょう", gloss: "today", kanji: [["今", "きょう"], ["日", null]] }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("休み", { lemma: "休み", pos: "noun", reading: "やすみ", gloss: "day off", kanji: [["休", "やす"]] }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
  ja("朝", { pos: "noun", reading: "あさ", gloss: "morning", kanji: [["朝", "あさ"]] }),
  punct("、"),
  ja("水", { pos: "noun", reading: "みず", gloss: "water", kanji: [["水", "みず"]] }),
  ja("を", { pos: "particle", role: "object", detail: "case", gloss: "object marker" }),
  ja("飲み", { lemma: "飲む", pos: "verb", reading: "のみ", gloss: "to drink", role: "verb", cid: 1, conj: POLITE_PRES("飲み"), kanji: [["飲", "の"]] }),
  ja("ます", { lemma: "ます", pos: "aux", role: "aux", gloss: "polite marker", cid: 1, conj: POLITE_PRES("飲み") }),
  punct("。"),
  ja("これ", { pos: "pronoun", gloss: "this" }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("パン", { pos: "noun", gloss: "bread" }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
  ja("パン", { pos: "noun", gloss: "bread" }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("美味しい", { pos: "i-adj", reading: "おいしい", role: "adj", gloss: "delicious", kanji: [["美", "おい"], ["味", "し"]] }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
  ja("母", { pos: "noun", reading: "はは", gloss: "mother", kanji: [["母", "はは"]] }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("家", { pos: "noun", reading: "いえ", gloss: "house; home", kanji: [["家", "いえ"]] }),
  ja("に", { pos: "particle", role: "particle", detail: "case", gloss: "at; in" }),
  ja("い", { lemma: "いる", pos: "verb", gloss: "to be (animate)", role: "verb", cid: 2, conj: POLITE_PRES("い") }),
  ja("ます", { lemma: "ます", pos: "aux", role: "aux", gloss: "polite marker", cid: 2, conj: POLITE_PRES("い") }),
  punct("。"),
  ja("母", { pos: "noun", reading: "はは", gloss: "mother", kanji: [["母", "はは"]] }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("元気", { pos: "na-adj", reading: "げんき", role: "adj", gloss: "cheerful; healthy", kanji: [["元", "げん"], ["気", "き"]] }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
  ja("これ", { pos: "pronoun", gloss: "this" }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("お茶", { lemma: "お茶", pos: "noun", reading: "おちゃ", gloss: "tea", kanji: [["茶", "ちゃ"]] }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
  ja("お茶", { lemma: "お茶", pos: "noun", reading: "おちゃ", gloss: "tea", kanji: [["茶", "ちゃ"]] }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("いい", { lemma: "良い", pos: "i-adj", role: "adj", gloss: "good" }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
  ja("私", { pos: "pronoun", reading: "わたし", gloss: "I; me", kanji: [["私", "わたし"]] }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("本", { pos: "noun", reading: "ほん", gloss: "book", kanji: [["本", "ほん"]] }),
  ja("を", { pos: "particle", role: "object", detail: "case", gloss: "object marker" }),
  ja("読み", { lemma: "読む", pos: "verb", reading: "よみ", gloss: "to read", role: "verb", cid: 3, conj: POLITE_PRES("読み"), kanji: [["読", "よ"]] }),
  ja("ます", { lemma: "ます", pos: "aux", role: "aux", gloss: "polite marker", cid: 3, conj: POLITE_PRES("読み") }),
  punct("。"),
  ja("本", { pos: "noun", reading: "ほん", gloss: "book", kanji: [["本", "ほん"]] }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("新しい", { pos: "i-adj", reading: "あたらしい", role: "adj", gloss: "new", kanji: [["新", "あたら"]] }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
  ja("これ", { pos: "pronoun", gloss: "this" }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("りんご", { pos: "noun", gloss: "apple" }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
  ja("りんご", { pos: "noun", gloss: "apple" }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("美味しい", { pos: "i-adj", reading: "おいしい", role: "adj", gloss: "delicious", kanji: [["美", "おい"], ["味", "し"]] }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
  ja("家", { pos: "noun", reading: "いえ", gloss: "house; home", kanji: [["家", "いえ"]] }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("きれい", { pos: "na-adj", role: "adj", gloss: "clean; pretty" }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
];

const JA_ICHIBA: Token[] = [
  ja("今日", { pos: "noun", reading: "きょう", gloss: "today", kanji: [["今", "きょう"], ["日", null]] }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("金曜日", { pos: "noun", reading: "きんようび", level: "A2", gloss: "Friday", kanji: [["金", "きん"], ["曜", "よう"], ["日", "び"]] }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
  ja("母", { pos: "noun", reading: "はは", gloss: "mother", kanji: [["母", "はは"]] }),
  ja("と", { pos: "particle", role: "particle", detail: "case", gloss: "and; with" }),
  ja("一緒", { pos: "noun", reading: "いっしょ", level: "A2", gloss: "together", kanji: [["一", "いっ"], ["緒", "しょ"]] }),
  ja("に", { pos: "particle", role: "particle", detail: "case", gloss: "to; at" }),
  ja("市場", { pos: "noun", reading: "いちば", level: "A2", gloss: "market", kanji: [["市", "いち"], ["場", "ば"]] }),
  ja("に", { pos: "particle", role: "particle", detail: "case", gloss: "to; at" }),
  ja("行き", { lemma: "行く", pos: "verb", reading: "いき", gloss: "to go", role: "verb", cid: 1, conj: POLITE_PRES("行き"), kanji: [["行", "い"]] }),
  ja("ます", { lemma: "ます", pos: "aux", role: "aux", gloss: "polite marker", cid: 1, conj: POLITE_PRES("行き") }),
  punct("。"),
  ja("市場", { pos: "noun", reading: "いちば", level: "A2", gloss: "market", kanji: [["市", "いち"], ["場", "ば"]] }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("家", { pos: "noun", reading: "いえ", gloss: "house; home", kanji: [["家", "いえ"]] }),
  ja("の", { pos: "particle", role: "particle", detail: "case", gloss: "of; ’s" }),
  ja("近く", { pos: "noun", reading: "ちかく", level: "A2", gloss: "near; the vicinity", kanji: [["近", "ちか"]] }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
  ja("朝", { pos: "noun", reading: "あさ", gloss: "morning", kanji: [["朝", "あさ"]] }),
  ja("早く", { lemma: "早い", pos: "i-adj", reading: "はやく", role: "adj", gloss: "early", kanji: [["早", "はや"]] }),
  ja("起き", { lemma: "起きる", pos: "verb", reading: "おき", level: "A2", gloss: "to get up", role: "verb", cid: 2, conj: POLITE_PAST("起き"), kanji: [["起", "お"]] }),
  ja("まし", { lemma: "ます", pos: "aux", role: "aux", gloss: "polite marker", cid: 2, conj: POLITE_PAST("起き") }),
  ja("た", { pos: "aux", role: "aux", gloss: "past tense", cid: 2, conj: POLITE_PAST("起き") }),
  punct("。"),
  ja("りんご", { pos: "noun", gloss: "apple" }),
  ja("を", { pos: "particle", role: "object", detail: "case", gloss: "object marker" }),
  ja("二つ", { pos: "noun", reading: "ふたつ", gloss: "two (things)", kanji: [["二", "ふた"]] }),
  ja("買い", { lemma: "買う", pos: "verb", reading: "かい", gloss: "to buy", role: "verb", cid: 3, conj: POLITE_PAST("買い"), kanji: [["買", "か"]] }),
  ja("まし", { lemma: "ます", pos: "aux", role: "aux", gloss: "polite marker", cid: 3, conj: POLITE_PAST("買い") }),
  ja("た", { pos: "aux", role: "aux", gloss: "past tense", cid: 3, conj: POLITE_PAST("買い") }),
  punct("。"),
  ja("パン", { pos: "noun", gloss: "bread" }),
  ja("も", { pos: "particle", role: "particle", detail: "binding", gloss: "also" }),
  ja("買い", { lemma: "買う", pos: "verb", reading: "かい", gloss: "to buy", role: "verb", cid: 4, conj: POLITE_PAST("買い"), kanji: [["買", "か"]] }),
  ja("まし", { lemma: "ます", pos: "aux", role: "aux", gloss: "polite marker", cid: 4, conj: POLITE_PAST("買い") }),
  ja("た", { pos: "aux", role: "aux", gloss: "past tense", cid: 4, conj: POLITE_PAST("買い") }),
  punct("。"),
  ja("市場", { pos: "noun", reading: "いちば", level: "A2", gloss: "market", kanji: [["市", "いち"], ["場", "ば"]] }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("人", { pos: "noun", reading: "ひと", gloss: "person", kanji: [["人", "ひと"]] }),
  ja("が", { pos: "particle", role: "subject", detail: "case", gloss: "subject marker" }),
  ja("多い", { pos: "i-adj", reading: "おおい", role: "adj", gloss: "many", kanji: [["多", "おお"]] }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
  ja("それから", { pos: "adverb", role: "adverb", level: "A2", gloss: "after that" }),
  ja("家", { pos: "noun", reading: "いえ", gloss: "house; home", kanji: [["家", "いえ"]] }),
  ja("に", { pos: "particle", role: "particle", detail: "case", gloss: "to; at" }),
  ja("帰り", { lemma: "帰る", pos: "verb", reading: "かえり", level: "A2", gloss: "to return home", role: "verb", cid: 5, conj: POLITE_PRES("帰り"), kanji: [["帰", "かえ"]] }),
  ja("ます", { lemma: "ます", pos: "aux", role: "aux", gloss: "polite marker", cid: 5, conj: POLITE_PRES("帰り") }),
  punct("。"),
];

const JA_DENSHA: Token[] = [
  ja("今", { pos: "noun", reading: "いま", gloss: "now", kanji: [["今", "いま"]] }),
  punct("、"),
  ja("電車", { pos: "noun", reading: "でんしゃ", gloss: "train", kanji: [["電", "でん"], ["車", "しゃ"]] }),
  ja("の", { pos: "particle", role: "particle", detail: "case", gloss: "of; ’s" }),
  ja("中", { pos: "noun", reading: "なか", gloss: "inside", kanji: [["中", "なか"]] }),
  ja("で", { pos: "particle", role: "particle", detail: "case", gloss: "at; in (place of action)" }),
  ja("本", { pos: "noun", reading: "ほん", gloss: "book", kanji: [["本", "ほん"]] }),
  ja("を", { pos: "particle", role: "object", detail: "case", gloss: "object marker" }),
  ja("読ん", { lemma: "読む", pos: "verb", reading: "よん", gloss: "to read", role: "verb", cid: 1, conj: TE_IRU("読ん"), kanji: [["読", "よ"]] }),
  ja("で", { pos: "particle", role: "aux", detail: "conjunctive", gloss: "te-form", cid: 1, conj: TE_IRU("読ん") }),
  ja("い", { lemma: "いる", pos: "aux", role: "aux", gloss: "progressive", cid: 1, conj: TE_IRU("読ん") }),
  ja("ます", { lemma: "ます", pos: "aux", role: "aux", gloss: "polite marker", cid: 1, conj: TE_IRU("読ん") }),
  punct("。"),
  ja("隣", { pos: "noun", reading: "となり", level: "B1", gloss: "next to; neighbour", kanji: [["隣", "となり"]] }),
  ja("の", { pos: "particle", role: "particle", detail: "case", gloss: "of; ’s" }),
  ja("人", { pos: "noun", reading: "ひと", gloss: "person", kanji: [["人", "ひと"]] }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("窓", { pos: "noun", reading: "まど", level: "A2", gloss: "window", kanji: [["窓", "まど"]] }),
  ja("を", { pos: "particle", role: "object", detail: "case", gloss: "object marker" }),
  ja("見", { lemma: "見る", pos: "verb", reading: "み", gloss: "to see; to look", role: "verb", cid: 2, conj: TE_IRU("見"), kanji: [["見", "み"]] }),
  ja("て", { pos: "particle", role: "aux", detail: "conjunctive", gloss: "te-form", cid: 2, conj: TE_IRU("見") }),
  ja("い", { lemma: "いる", pos: "aux", role: "aux", gloss: "progressive", cid: 2, conj: TE_IRU("見") }),
  ja("ます", { lemma: "ます", pos: "aux", role: "aux", gloss: "polite marker", cid: 2, conj: TE_IRU("見") }),
  punct("。"),
  ja("駅", { pos: "noun", reading: "えき", gloss: "station", kanji: [["駅", "えき"]] }),
  ja("に", { pos: "particle", role: "particle", detail: "case", gloss: "to; at" }),
  ja("着い", { lemma: "着く", pos: "verb", reading: "つい", level: "A2", gloss: "to arrive", role: "verb", cid: 3, conj: [{ text: "着い", label: "stem" }, { text: "たら", label: "conditional" }], kanji: [["着", "つ"]] }),
  ja("たら", { pos: "particle", role: "particle", detail: "conjunctive", level: "B1", gloss: "when; if", cid: 3, conj: [{ text: "着い", label: "stem" }, { text: "たら", label: "conditional" }] }),
  punct("、"),
  ja("友達", { pos: "noun", reading: "ともだち", gloss: "friend", kanji: [["友", "とも"], ["達", "だち"]] }),
  ja("に", { pos: "particle", role: "particle", detail: "case", gloss: "to; at" }),
  ja("会い", { lemma: "会う", pos: "verb", reading: "あい", gloss: "to meet", role: "verb", cid: 4, conj: POLITE_PRES("会い"), kanji: [["会", "あ"]] }),
  ja("ます", { lemma: "ます", pos: "aux", role: "aux", gloss: "polite marker", cid: 4, conj: POLITE_PRES("会い") }),
  punct("。"),
  ja("友達", { pos: "noun", reading: "ともだち", gloss: "friend", kanji: [["友", "とも"], ["達", "だち"]] }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("京都", { pos: "noun", reading: "きょうと", gloss: "Kyoto", level: null, kanji: [["京", "きょう"], ["都", "と"]] }),
  ja("で", { pos: "particle", role: "particle", detail: "case", gloss: "at; in (place of action)" }),
  ja("働い", { lemma: "働く", pos: "verb", reading: "はたらい", level: "A2", gloss: "to work", role: "verb", cid: 5, conj: TE_IRU("働い"), kanji: [["働", "はたら"]] }),
  ja("て", { pos: "particle", role: "aux", detail: "conjunctive", gloss: "te-form", cid: 5, conj: TE_IRU("働い") }),
  ja("い", { lemma: "いる", pos: "aux", role: "aux", gloss: "progressive", cid: 5, conj: TE_IRU("働い") }),
  ja("ます", { lemma: "ます", pos: "aux", role: "aux", gloss: "polite marker", cid: 5, conj: TE_IRU("働い") }),
  punct("。"),
  ja("もし", { pos: "adverb", role: "adverb", level: "B1", gloss: "if" }),
  ja("雨", { pos: "noun", reading: "あめ", gloss: "rain", kanji: [["雨", "あめ"]] }),
  ja("なら", { pos: "particle", role: "particle", detail: "conjunctive", level: "B1", gloss: "if (it is)" }),
  punct("、"),
  ja("ホテル", { pos: "noun", gloss: "hotel" }),
  ja("で", { pos: "particle", role: "particle", detail: "case", gloss: "at; in (place of action)" }),
  ja("待ち", { lemma: "待つ", pos: "verb", reading: "まち", gloss: "to wait", role: "verb", cid: 6, conj: POLITE_PRES("待ち"), kanji: [["待", "ま"]] }),
  ja("ます", { lemma: "ます", pos: "aux", role: "aux", gloss: "polite marker", cid: 6, conj: POLITE_PRES("待ち") }),
  punct("。"),
  ja("本", { pos: "noun", reading: "ほん", gloss: "book", kanji: [["本", "ほん"]] }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("新しい", { pos: "i-adj", reading: "あたらしい", role: "adj", gloss: "new", kanji: [["新", "あたら"]] }),
  ja("し", { pos: "particle", role: "particle", detail: "conjunctive", gloss: "and (listing reasons)" }),
  punct("、"),
  ja("とても", { pos: "adverb", role: "adverb", gloss: "very" }),
  ja("面白い", { pos: "i-adj", reading: "おもしろい", role: "adj", level: "A2", gloss: "interesting", kanji: [["面", "おも"], ["白", "しろ"]] }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
  ja("会社", { pos: "noun", reading: "かいしゃ", gloss: "company", kanji: [["会", "かい"], ["社", "しゃ"]] }),
  ja("の", { pos: "particle", role: "particle", detail: "case", gloss: "of; ’s" }),
  ja("仕事", { pos: "noun", reading: "しごと", gloss: "work; job" }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("忙しい", { pos: "i-adj", reading: "いそがしい", role: "adj", level: "A2", gloss: "busy", kanji: [["忙", "いそが"]] }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  ja("が", { pos: "particle", role: "particle", detail: "conjunctive", gloss: "but" }),
  punct("、"),
  ja("今日", { pos: "noun", reading: "きょう", gloss: "today", kanji: [["今", "きょう"], ["日", null]] }),
  ja("は", { pos: "particle", role: "topic", detail: "binding", gloss: "topic marker" }),
  ja("休み", { pos: "noun", reading: "やすみ", gloss: "day off", kanji: [["休", "やす"]] }),
  ja("です", { pos: "aux", role: "aux", gloss: "is (polite)" }),
  punct("。"),
];

const RU_ANNA: Token[] = [
  ru("Я", { lemma: "я", pos: "NPRO", case: "nom", number: "sg", gloss: "I" }),
  ru("студент", { pos: "NOUN", case: "nom", gender: "masc", number: "sg", gloss: "student", ws: "" }),
  punct(".", " "),
  ru("Это", { lemma: "это", pos: "NPRO", case: "nom", number: "sg", gloss: "this" }),
  ru("книга", { pos: "NOUN", case: "nom", gender: "fem", number: "sg", gloss: "book", ws: "" }),
  punct(".", " "),
  ru("Книга", { lemma: "книга", pos: "NOUN", case: "nom", gender: "fem", number: "sg", gloss: "book" }),
  ru("новая", { lemma: "новый", pos: "ADJF", case: "nom", gender: "fem", number: "sg", gloss: "new", role: "adj", ws: "" }),
  punct(".", " "),
  ru("Мама", { lemma: "мама", pos: "NOUN", case: "nom", gender: "fem", number: "sg", gloss: "mom" }),
  ru("здесь", { pos: "ADVB", gloss: "here", role: "adverb", ws: "" }),
  punct(".", " "),
  ru("Это", { lemma: "это", pos: "NPRO", case: "nom", number: "sg", gloss: "this" }),
  ru("вода", { pos: "NOUN", case: "nom", gender: "fem", number: "sg", gloss: "water", ws: "" }),
  punct(".", " "),
  ru("Вода", { lemma: "вода", pos: "NOUN", case: "nom", gender: "fem", number: "sg", gloss: "water" }),
  ru("холодная", { lemma: "холодный", pos: "ADJF", case: "nom", gender: "fem", number: "sg", gloss: "cold", role: "adj", ws: "" }),
  punct(".", " "),
  ru("Это", { lemma: "это", pos: "NPRO", case: "nom", number: "sg", gloss: "this" }),
  ru("чай", { pos: "NOUN", case: "nom", gender: "masc", number: "sg", gloss: "tea", ws: "" }),
  punct(".", " "),
  ru("Чай", { lemma: "чай", pos: "NOUN", case: "nom", gender: "masc", number: "sg", gloss: "tea" }),
  ru("хороший", { lemma: "хороший", pos: "ADJF", case: "nom", gender: "masc", number: "sg", gloss: "good", role: "adj", ws: "" }),
  punct(".", " "),
  ru("Анна", { pos: "NOUN", case: "nom", gender: "fem", number: "sg", gloss: "Anna", level: null }),
  ru("здесь", { pos: "ADVB", gloss: "here", role: "adverb", ws: "" }),
  punct(".", " "),
  ru("Анна", { pos: "NOUN", case: "nom", gender: "fem", number: "sg", gloss: "Anna", level: null }),
  ru("студентка", { pos: "NOUN", case: "nom", gender: "fem", number: "sg", gloss: "student (f.)", ws: "" }),
  punct(".", " "),
  ru("День", { lemma: "день", pos: "NOUN", case: "nom", gender: "masc", number: "sg", gloss: "day" }),
  ru("хороший", { lemma: "хороший", pos: "ADJF", case: "nom", gender: "masc", number: "sg", gloss: "good", role: "adj", ws: "" }),
  punct("."),
];

const RU_POEZD: Token[] = [
  ru("Сегодня", { pos: "ADVB", gloss: "today", role: "adverb" }),
  ru("я", { pos: "NPRO", case: "nom", number: "sg", gloss: "I" }),
  ru("еду", { lemma: "ехать", pos: "VERB", aspect: "impf", tense: "pres", number: "sg", gloss: "to go (by vehicle)", role: "verb" }),
  ru("в", { pos: "PREP", gloss: "to; in", role: "particle" }),
  ru("город", { pos: "NOUN", case: "acc", gender: "masc", number: "sg", gloss: "city", ws: "" }),
  punct(".", " "),
  ru("Вокзал", { pos: "NOUN", case: "nom", gender: "masc", number: "sg", level: "A2", gloss: "station" }),
  ru("рядом", { pos: "ADVB", gloss: "nearby", role: "adverb", ws: "" }),
  punct(".", " "),
  ru("Я", { lemma: "я", pos: "NPRO", case: "nom", number: "sg", gloss: "I" }),
  ru("покупаю", { lemma: "покупать", pos: "VERB", aspect: "impf", tense: "pres", number: "sg", gloss: "to buy", role: "verb" }),
  ru("билет", { pos: "NOUN", case: "acc", gender: "masc", number: "sg", level: "A2", gloss: "ticket", ws: "" }),
  punct(".", " "),
  ru("В", { lemma: "в", pos: "PREP", gloss: "in", role: "particle" }),
  ru("поезде", { lemma: "поезд", pos: "NOUN", case: "prep", gender: "masc", number: "sg", level: "A2", gloss: "train" }),
  ru("я", { pos: "NPRO", case: "nom", number: "sg", gloss: "I" }),
  ru("читаю", { lemma: "читать", pos: "VERB", aspect: "impf", tense: "pres", number: "sg", gloss: "to read", role: "verb" }),
  ru("книгу", { lemma: "книга", pos: "NOUN", case: "acc", gender: "fem", number: "sg", gloss: "book" }),
  ru("и", { pos: "CONJ", gloss: "and", role: "particle" }),
  ru("пью", { lemma: "пить", pos: "VERB", aspect: "impf", tense: "pres", number: "sg", gloss: "to drink", role: "verb" }),
  ru("воду", { lemma: "вода", pos: "NOUN", case: "acc", gender: "fem", number: "sg", gloss: "water", ws: "" }),
  punct(".", " "),
  ru("Вчера", { pos: "ADVB", gloss: "yesterday", role: "adverb" }),
  ru("я", { pos: "NPRO", case: "nom", number: "sg", gloss: "I" }),
  ru("был", { lemma: "быть", pos: "VERB", tense: "past", gender: "masc", number: "sg", gloss: "to be", role: "verb" }),
  ru("дома", { pos: "ADVB", gloss: "at home", role: "adverb", ws: "" }),
  punct(".", " "),
  ru("Друг", { lemma: "друг", pos: "NOUN", case: "nom", gender: "masc", number: "sg", gloss: "friend" }),
  ru("ждёт", { lemma: "ждать", pos: "VERB", aspect: "impf", tense: "pres", number: "sg", level: "A2", gloss: "to wait", role: "verb" }),
  ru("меня", { lemma: "я", pos: "NPRO", case: "acc", number: "sg", gloss: "me" }),
  ru("на", { pos: "PREP", gloss: "at; on", role: "particle" }),
  ru("вокзале", { lemma: "вокзал", pos: "NOUN", case: "prep", gender: "masc", number: "sg", level: "A2", gloss: "station", ws: "" }),
  punct(".", " "),
  ru("Город", { lemma: "город", pos: "NOUN", case: "nom", gender: "masc", number: "sg", gloss: "city" }),
  ru("большой", { pos: "ADJF", case: "nom", gender: "masc", number: "sg", gloss: "big", role: "adj", ws: "" }),
  punct("."),
];

const RU_KNIGA: Token[] = [
  ru("Сейчас", { pos: "ADVB", gloss: "now", role: "adverb" }),
  ru("я", { pos: "NPRO", case: "nom", number: "sg", gloss: "I" }),
  ru("еду", { lemma: "ехать", pos: "VERB", aspect: "impf", tense: "pres", number: "sg", gloss: "to go (by vehicle)", role: "verb" }),
  ru("в", { pos: "PREP", gloss: "in", role: "particle" }),
  ru("поезде", { lemma: "поезд", pos: "NOUN", case: "prep", gender: "masc", number: "sg", level: "A2", gloss: "train" }),
  ru("и", { pos: "CONJ", gloss: "and", role: "particle" }),
  ru("читаю", { lemma: "читать", pos: "VERB", aspect: "impf", tense: "pres", number: "sg", gloss: "to read", role: "verb" }),
  ru("книгу", { lemma: "книга", pos: "NOUN", case: "acc", gender: "fem", number: "sg", gloss: "book", ws: "" }),
  punct(".", " "),
  ru("Если", { pos: "CONJ", gloss: "if", role: "particle", level: "B1" }),
  ru("друг", { pos: "NOUN", case: "nom", gender: "masc", number: "sg", gloss: "friend" }),
  ru("позвонит", { lemma: "позвонить", pos: "VERB", aspect: "perf", tense: "fut", number: "sg", level: "B1", gloss: "to call", role: "verb" }),
  punct(",", " "),
  ru("я", { pos: "NPRO", case: "nom", number: "sg", gloss: "I" }),
  ru("выйду", { lemma: "выйти", pos: "VERB", aspect: "perf", tense: "fut", number: "sg", level: "B1", gloss: "to get off; to go out", role: "verb" }),
  ru("на", { pos: "PREP", gloss: "at; on", role: "particle" }),
  ru("вокзале", { lemma: "вокзал", pos: "NOUN", case: "prep", gender: "masc", number: "sg", level: "A2", gloss: "station", ws: "" }),
  punct(".", " "),
  ru("Работа", { lemma: "работа", pos: "NOUN", case: "nom", gender: "fem", number: "sg", gloss: "work" }),
  ru("сегодня", { pos: "ADVB", gloss: "today", role: "adverb" }),
  ru("не", { pos: "PRCL", gloss: "not" }),
  ru("ждёт", { lemma: "ждать", pos: "VERB", aspect: "impf", tense: "pres", number: "sg", level: "A2", gloss: "to wait", role: "verb" }),
  ru("меня", { lemma: "я", pos: "NPRO", case: "acc", number: "sg", gloss: "me" }),
  punct(",", " "),
  ru("потому", { pos: "CONJ", gloss: "because", role: "particle", level: "B1" }),
  ru("что", { pos: "CONJ", gloss: "that", role: "particle" }),
  ru("это", { pos: "NPRO", case: "nom", number: "sg", gloss: "this" }),
  ru("выходной", { pos: "NOUN", case: "nom", gender: "masc", number: "sg", level: "A2", gloss: "day off", ws: "" }),
  punct(".", " "),
  ru("Когда", { pos: "CONJ", gloss: "when", role: "particle", level: "B1" }),
  ru("поезд", { pos: "NOUN", case: "nom", gender: "masc", number: "sg", level: "A2", gloss: "train" }),
  ru("остановится", { lemma: "остановиться", pos: "VERB", aspect: "perf", tense: "fut", number: "sg", level: "B1", gloss: "to stop", role: "verb" }),
  punct(",", " "),
  ru("я", { pos: "NPRO", case: "nom", number: "sg", gloss: "I" }),
  ru("куплю", { lemma: "купить", pos: "VERB", aspect: "perf", tense: "fut", number: "sg", gloss: "to buy", role: "verb" }),
  ru("воду", { lemma: "вода", pos: "NOUN", case: "acc", gender: "fem", number: "sg", gloss: "water", ws: "" }),
  punct(".", " "),
  ru("Город", { lemma: "город", pos: "NOUN", case: "nom", gender: "masc", number: "sg", gloss: "city" }),
  ru("уже", { pos: "ADVB", gloss: "already", role: "adverb" }),
  ru("близко", { pos: "ADVB", gloss: "close; nearby", role: "adverb", ws: "" }),
  punct("."),
];

const IT_CASA: Token[] = [
  it("Anna", { pos: "PROPN", gloss: "Anna", level: null }),
  it("è", { lemma: "essere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be", role: "verb" }),
  it("studentessa", { pos: "NOUN", gender: "fem", number: "sg", gloss: "student", ws: "" }),
  punct(".", " "),
  it("Anna", { pos: "PROPN", gloss: "Anna", level: null }),
  it("è", { lemma: "essere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be", role: "verb" }),
  it("qui", { pos: "ADV", gloss: "here", role: "adverb", ws: "" }),
  punct(".", " "),
  it("Questa", { lemma: "questo", pos: "DET", gender: "fem", number: "sg", gloss: "this" }),
  it("è", { lemma: "essere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be", role: "verb" }),
  it("una", { lemma: "un", pos: "DET", gender: "fem", number: "sg", gloss: "a" }),
  it("stanza", { pos: "NOUN", gender: "fem", number: "sg", gloss: "room", ws: "" }),
  punct(".", " "),
  it("La", { lemma: "il", pos: "DET", gender: "fem", number: "sg", gloss: "the" }),
  it("stanza", { pos: "NOUN", gender: "fem", number: "sg", gloss: "room" }),
  it("è", { lemma: "essere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be", role: "verb" }),
  it("nuova", { lemma: "nuovo", pos: "ADJ", gender: "fem", number: "sg", gloss: "new", role: "adj", ws: "" }),
  punct(".", " "),
  it("Questo", { lemma: "questo", pos: "DET", gender: "masc", number: "sg", gloss: "this" }),
  it("è", { lemma: "essere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be", role: "verb" }),
  it("un", { pos: "DET", gender: "masc", number: "sg", gloss: "a" }),
  it("libro", { pos: "NOUN", gender: "masc", number: "sg", gloss: "book", ws: "" }),
  punct(".", " "),
  it("Il", { lemma: "il", pos: "DET", gender: "masc", number: "sg", gloss: "the" }),
  it("libro", { pos: "NOUN", gender: "masc", number: "sg", gloss: "book" }),
  it("è", { lemma: "essere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be", role: "verb" }),
  it("nuovo", { pos: "ADJ", gender: "masc", number: "sg", gloss: "new", role: "adj", ws: "" }),
  punct(".", " "),
  it("Questo", { lemma: "questo", pos: "DET", gender: "masc", number: "sg", gloss: "this" }),
  it("è", { lemma: "essere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be", role: "verb" }),
  it("tè", { pos: "NOUN", gender: "masc", number: "sg", gloss: "tea", ws: "" }),
  punct(".", " "),
  it("Il", { lemma: "il", pos: "DET", gender: "masc", number: "sg", gloss: "the" }),
  it("tè", { pos: "NOUN", gender: "masc", number: "sg", gloss: "tea" }),
  it("è", { lemma: "essere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be", role: "verb" }),
  it("buono", { pos: "ADJ", gender: "masc", number: "sg", gloss: "good", role: "adj", ws: "" }),
  punct(".", " "),
  it("La", { lemma: "il", pos: "DET", gender: "fem", number: "sg", gloss: "the" }),
  it("mamma", { pos: "NOUN", gender: "fem", number: "sg", gloss: "mom" }),
  it("è", { lemma: "essere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be", role: "verb" }),
  it("qui", { pos: "ADV", gloss: "here", role: "adverb", ws: "" }),
  punct(".", " "),
  it("Io", { lemma: "io", pos: "PRON", gloss: "I" }),
  it("sono", { lemma: "essere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be", role: "verb" }),
  it("studente", { pos: "NOUN", gender: "masc", number: "sg", gloss: "student", ws: "" }),
  punct("."),
];

const IT_TRENO: Token[] = [
  it("Oggi", { pos: "ADV", gloss: "today", role: "adverb" }),
  it("vado", { lemma: "andare", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to go", role: "verb" }),
  it("in", { pos: "ADP", gloss: "to; in", role: "particle" }),
  it("città", { pos: "NOUN", gender: "fem", number: "sg", gloss: "city", ws: "" }),
  punct(".", " "),
  it("La", { lemma: "il", pos: "DET", gender: "fem", number: "sg", gloss: "the" }),
  it("stazione", { pos: "NOUN", gender: "fem", number: "sg", gloss: "station" }),
  it("è", { lemma: "essere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be", role: "verb" }),
  it("vicina", { lemma: "vicino", pos: "ADJ", gender: "fem", number: "sg", gloss: "nearby", role: "adj", ws: "" }),
  punct(".", " "),
  it("Compro", { lemma: "comprare", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to buy", role: "verb" }),
  it("un", { pos: "DET", gender: "masc", number: "sg", gloss: "a" }),
  it("biglietto", { pos: "NOUN", gender: "masc", number: "sg", level: "A2", gloss: "ticket", ws: "" }),
  punct(".", " "),
  it("Sul", { lemma: "su", pos: "ADP", gloss: "on", role: "particle" }),
  it("treno", { pos: "NOUN", gender: "masc", number: "sg", gloss: "train" }),
  it("leggo", { lemma: "leggere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to read", role: "verb" }),
  it("un", { pos: "DET", gender: "masc", number: "sg", gloss: "a" }),
  it("libro", { pos: "NOUN", gender: "masc", number: "sg", gloss: "book" }),
  it("e", { pos: "CCONJ", gloss: "and", role: "particle" }),
  it("bevo", { lemma: "bere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to drink", role: "verb" }),
  it("acqua", { pos: "NOUN", gender: "fem", number: "sg", gloss: "water", ws: "" }),
  punct(".", " "),
  it("Ieri", { pos: "ADV", gloss: "yesterday", role: "adverb" }),
  it("sono", { lemma: "essere", pos: "AUX", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be" }),
  it("stato", { lemma: "essere", pos: "VERB", tense: "past", form: "part", gender: "masc", number: "sg", level: "A2", gloss: "been", role: "verb" }),
  it("a", { pos: "ADP", gloss: "at", role: "particle" }),
  it("casa", { pos: "NOUN", gender: "fem", number: "sg", gloss: "house / home", ws: "" }),
  punct(".", " "),
  it("Un", { pos: "DET", gender: "masc", number: "sg", gloss: "a" }),
  it("amico", { pos: "NOUN", gender: "masc", number: "sg", gloss: "friend" }),
  it("aspetta", { lemma: "aspettare", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to wait", role: "verb" }),
  it("alla", { lemma: "a", pos: "ADP", gloss: "at", role: "particle" }),
  it("stazione", { pos: "NOUN", gender: "fem", number: "sg", gloss: "station", ws: "" }),
  punct(".", " "),
  it("La", { lemma: "il", pos: "DET", gender: "fem", number: "sg", gloss: "the" }),
  it("città", { pos: "NOUN", gender: "fem", number: "sg", gloss: "city" }),
  it("è", { lemma: "essere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be", role: "verb" }),
  it("grande", { pos: "ADJ", number: "sg", gloss: "large", role: "adj", ws: "" }),
  punct("."),
];

const IT_LIBRO: Token[] = [
  it("Adesso", { pos: "ADV", gloss: "now", role: "adverb" }),
  it("sono", { lemma: "essere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be", role: "verb" }),
  it("sul", { lemma: "su", pos: "ADP", gloss: "on", role: "particle" }),
  it("treno", { pos: "NOUN", gender: "masc", number: "sg", gloss: "train" }),
  it("e", { pos: "CCONJ", gloss: "and", role: "particle" }),
  it("leggo", { lemma: "leggere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to read", role: "verb" }),
  it("un", { pos: "DET", gender: "masc", number: "sg", gloss: "a" }),
  it("libro", { pos: "NOUN", gender: "masc", number: "sg", gloss: "book", ws: "" }),
  punct(".", " "),
  it("Quando", { pos: "SCONJ", gloss: "when", role: "particle", level: "B1" }),
  it("ero", { lemma: "essere", pos: "VERB", tense: "impf", mood: "indc", form: "fin", number: "sg", level: "B1", gloss: "to be", role: "verb" }),
  it("bambino", { pos: "NOUN", gender: "masc", number: "sg", gloss: "child" }),
  punct(",", " "),
  it("leggevo", { lemma: "leggere", pos: "VERB", tense: "impf", mood: "indc", form: "fin", number: "sg", level: "B1", gloss: "to read", role: "verb" }),
  it("sempre", { pos: "ADV", gloss: "always", role: "adverb" }),
  it("sul", { lemma: "su", pos: "ADP", gloss: "on", role: "particle" }),
  it("treno", { pos: "NOUN", gender: "masc", number: "sg", gloss: "train", ws: "" }),
  punct(".", " "),
  it("Il", { lemma: "il", pos: "DET", gender: "masc", number: "sg", gloss: "the" }),
  it("lavoro", { pos: "NOUN", gender: "masc", number: "sg", gloss: "work" }),
  it("oggi", { pos: "ADV", gloss: "today", role: "adverb" }),
  it("non", { pos: "ADV", gloss: "not" }),
  it("aspetta", { lemma: "aspettare", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to wait", role: "verb" }),
  punct(",", " "),
  it("perché", { pos: "SCONJ", gloss: "because", role: "particle", level: "A2" }),
  it("è", { lemma: "essere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be", role: "verb" }),
  it("domenica", { pos: "NOUN", gender: "fem", number: "sg", gloss: "Sunday", ws: "" }),
  punct(".", " "),
  it("Poi", { pos: "ADV", gloss: "then", role: "adverb" }),
  it("compro", { lemma: "comprare", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to buy", role: "verb" }),
  it("acqua", { pos: "NOUN", gender: "fem", number: "sg", gloss: "water" }),
  it("alla", { lemma: "a", pos: "ADP", gloss: "at", role: "particle" }),
  it("stazione", { pos: "NOUN", gender: "fem", number: "sg", gloss: "station", ws: "" }),
  punct(".", " "),
  it("La", { lemma: "il", pos: "DET", gender: "fem", number: "sg", gloss: "the" }),
  it("città", { pos: "NOUN", gender: "fem", number: "sg", gloss: "city" }),
  it("è", { lemma: "essere", pos: "VERB", tense: "pres", mood: "indc", form: "fin", number: "sg", gloss: "to be", role: "verb" }),
  it("già", { pos: "ADV", gloss: "already", role: "adverb" }),
  it("vicina", { lemma: "vicino", pos: "ADJ", gender: "fem", number: "sg", gloss: "nearby", role: "adj", ws: "" }),
  punct("."),
];

const AR_BAIT: Token[] = [
  ar("هذا", { pos: "DET", gloss: "this", reading: "هَذَا" }),
  ar("أحمد", { pos: "PROPN", gloss: "Ahmad", level: null, ws: "" }),
  punct(".", " "),
  ar("أحمد", { pos: "PROPN", gloss: "Ahmad", level: null }),
  ar("طالب", { pos: "NOUN", case: "nom", gender: "masc", number: "sg", state: "indef", gloss: "student", ws: "" }),
  punct(".", " "),
  ar("أحمد", { pos: "PROPN", gloss: "Ahmad", level: null }),
  ar("هنا", { pos: "ADV", gloss: "here", role: "adverb", ws: "" }),
  punct(".", " "),
  ar("هذا", { pos: "DET", gloss: "this" }),
  ar("بيت", { pos: "NOUN", case: "nom", gender: "masc", number: "sg", state: "indef", gloss: "house", root: BYT, ws: "" }),
  punct(".", " "),
  ar("البيت", { lemma: "بيت", pos: "NOUN", case: "nom", gender: "masc", number: "sg", state: "def", gloss: "house", reading: "البَيْتُ", root: BYT }),
  ar("كبير", { pos: "ADJ", gender: "masc", number: "sg", gloss: "big", role: "adj", ws: "" }),
  punct(".", " "),
  ar("هذه", { pos: "DET", gloss: "this (f.)" }),
  ar("غرفة", { pos: "NOUN", case: "nom", gender: "fem", number: "sg", state: "indef", gloss: "room", ws: "" }),
  punct(".", " "),
  ar("الغرفة", { lemma: "غرفة", pos: "NOUN", case: "nom", gender: "fem", number: "sg", state: "def", gloss: "room" }),
  ar("جديدة", { lemma: "جديد", pos: "ADJ", gender: "fem", number: "sg", gloss: "new", role: "adj", ws: "" }),
  punct(".", " "),
  ar("هذا", { pos: "DET", gloss: "this" }),
  ar("كتاب", { pos: "NOUN", case: "nom", gender: "masc", number: "sg", state: "indef", gloss: "book", root: KTB, ws: "" }),
  punct(".", " "),
  ar("الكتاب", { lemma: "كتاب", pos: "NOUN", case: "nom", gender: "masc", number: "sg", state: "def", gloss: "book", root: KTB }),
  ar("جديد", { pos: "ADJ", gender: "masc", number: "sg", gloss: "new", role: "adj", ws: "" }),
  punct(".", " "),
  ar("أمي", {
    lemma: "أم",
    pos: "NOUN",
    case: "nom",
    gender: "fem",
    number: "sg",
    state: "const",
    gloss: "mother",
    enclitic: "1s_poss",
    conj: [{ text: "أم", label: "stem" }, { text: "ي", label: "my" }],
  }),
  ar("هنا", { pos: "ADV", gloss: "here", role: "adverb", ws: "" }),
  punct(".", " "),
  ar("الشاي", { lemma: "شاي", pos: "NOUN", case: "nom", gender: "masc", number: "sg", state: "def", gloss: "tea" }),
  ar("جيد", { pos: "ADJ", gender: "masc", number: "sg", gloss: "good", role: "adj", ws: "" }),
  punct(".", " "),
  ar("الماء", { lemma: "ماء", pos: "NOUN", case: "nom", gender: "masc", number: "sg", state: "def", gloss: "water" }),
  ar("بارد", { pos: "ADJ", gender: "masc", number: "sg", gloss: "cold", role: "adj", ws: "" }),
  punct(".", " "),
  ar("أنا", { pos: "PRON", gloss: "I" }),
  ar("طالب", { pos: "NOUN", case: "nom", gender: "masc", number: "sg", state: "indef", gloss: "student", ws: "" }),
  punct("."),
];

const AR_QITAR: Token[] = [
  ar("اليوم", { lemma: "يوم", pos: "NOUN", case: "nom", gender: "masc", number: "sg", state: "def", gloss: "today" }),
  ar("أذهب", { lemma: "ذهب", pos: "VERB", tense: "pres", mood: "indc", voice: "act", person: "1", number: "sg", form: "I", gloss: "to go", role: "verb", reading: "أَذْهَبُ", root: DHB }),
  ar("إلى", { pos: "ADP", gloss: "to", role: "particle" }),
  ar("المدينة", { lemma: "مدينة", pos: "NOUN", case: "gen", gender: "fem", number: "sg", state: "def", gloss: "city", ws: "" }),
  punct(".", " "),
  ar("المحطة", { lemma: "محطة", pos: "NOUN", case: "nom", gender: "fem", number: "sg", state: "def", gloss: "station", level: "A2" }),
  ar("قريبة", { lemma: "قريب", pos: "ADJ", gender: "fem", number: "sg", gloss: "nearby", role: "adj", ws: "" }),
  punct(".", " "),
  ar("أشتري", { lemma: "اشترى", pos: "VERB", tense: "pres", mood: "indc", voice: "act", person: "1", number: "sg", form: "VIII", gloss: "to buy", role: "verb", reading: "أَشْتَرِي", root: SHR, level: "A2" }),
  ar("تذكرة", { pos: "NOUN", case: "acc", gender: "fem", number: "sg", state: "indef", gloss: "ticket", level: "A2", ws: "" }),
  punct(".", " "),
  ar("في", { pos: "ADP", gloss: "in", role: "particle" }),
  ar("القطار", { lemma: "قطار", pos: "NOUN", case: "gen", gender: "masc", number: "sg", state: "def", gloss: "train", level: "A2" }),
  ar("أقرأ", { lemma: "قرأ", pos: "VERB", tense: "pres", mood: "indc", voice: "act", person: "1", number: "sg", form: "I", gloss: "to read", role: "verb", reading: "أَقْرَأُ", root: QRA }),
  ar("كتابا", { lemma: "كتاب", pos: "NOUN", case: "acc", gender: "masc", number: "sg", state: "indef", gloss: "book", root: KTB }),
  ar("و", { pos: "CCONJ", gloss: "and", role: "particle" }),
  ar("أشرب", { lemma: "شرب", pos: "VERB", tense: "pres", mood: "indc", voice: "act", person: "1", number: "sg", form: "I", gloss: "to drink", role: "verb", reading: "أَشْرَبُ", root: SHRB }),
  ar("ماء", { pos: "NOUN", case: "acc", gender: "masc", number: "sg", state: "indef", gloss: "water", ws: "" }),
  punct(".", " "),
  ar("أمس", { pos: "ADV", gloss: "yesterday", role: "adverb", level: "A2" }),
  ar("كنت", { lemma: "كان", pos: "VERB", tense: "past", mood: "indc", voice: "act", person: "1", number: "sg", form: "I", gloss: "to be", role: "verb", root: KWN, level: "A2" }),
  ar("في", { pos: "ADP", gloss: "in", role: "particle" }),
  ar("البيت", { lemma: "بيت", pos: "NOUN", case: "gen", gender: "masc", number: "sg", state: "def", gloss: "house", root: BYT, ws: "" }),
  punct(".", " "),
  ar("صديق", { pos: "NOUN", case: "nom", gender: "masc", number: "sg", state: "indef", gloss: "friend" }),
  ar("ينتظر", { lemma: "انتظر", pos: "VERB", tense: "pres", mood: "indc", voice: "act", person: "3", number: "sg", gender: "masc", form: "VIII", gloss: "to wait", role: "verb", root: NZL, level: "A2" }),
  ar("في", { pos: "ADP", gloss: "in", role: "particle" }),
  ar("المحطة", { lemma: "محطة", pos: "NOUN", case: "gen", gender: "fem", number: "sg", state: "def", gloss: "station", level: "A2", ws: "" }),
  punct(".", " "),
  ar("المدينة", { lemma: "مدينة", pos: "NOUN", case: "nom", gender: "fem", number: "sg", state: "def", gloss: "city" }),
  ar("كبيرة", { lemma: "كبير", pos: "ADJ", gender: "fem", number: "sg", gloss: "large", role: "adj", ws: "" }),
  punct("."),
];

const AR_KITAB: Token[] = [
  ar("الآن", { pos: "ADV", gloss: "now", role: "adverb" }),
  ar("أنا", { pos: "PRON", gloss: "I" }),
  ar("في", { pos: "ADP", gloss: "in", role: "particle" }),
  ar("القطار", { lemma: "قطار", pos: "NOUN", case: "gen", gender: "masc", number: "sg", state: "def", gloss: "train", level: "A2" }),
  ar("و", { pos: "CCONJ", gloss: "and", role: "particle" }),
  ar("أقرأ", { lemma: "قرأ", pos: "VERB", tense: "pres", mood: "indc", voice: "act", person: "1", number: "sg", form: "I", gloss: "to read", role: "verb", reading: "أَقْرَأُ", root: QRA }),
  ar("كتابا", { lemma: "كتاب", pos: "NOUN", case: "acc", gender: "masc", number: "sg", state: "indef", gloss: "book", root: KTB, ws: "" }),
  punct(".", " "),
  ar("عندما", { pos: "ADV", gloss: "when", role: "adverb", level: "B1" }),
  ar("كنت", { lemma: "كان", pos: "VERB", tense: "past", mood: "indc", voice: "act", person: "1", number: "sg", form: "I", gloss: "to be", role: "verb", root: KWN, level: "A2" }),
  ar("صغيرا", { lemma: "صغير", pos: "ADJ", gender: "masc", number: "sg", gloss: "small; young", role: "adj", level: "A2" }),
  ar("كنت", { lemma: "كان", pos: "VERB", tense: "past", mood: "indc", voice: "act", person: "1", number: "sg", form: "I", gloss: "to be", role: "verb", root: KWN, level: "A2" }),
  ar("أقرأ", { lemma: "قرأ", pos: "VERB", tense: "pres", mood: "indc", voice: "act", person: "1", number: "sg", form: "I", gloss: "to read", role: "verb", reading: "أَقْرَأُ", root: QRA }),
  ar("في", { pos: "ADP", gloss: "in", role: "particle" }),
  ar("القطار", { lemma: "قطار", pos: "NOUN", case: "gen", gender: "masc", number: "sg", state: "def", gloss: "train", level: "A2" }),
  ar("دائما", { lemma: "دائم", pos: "ADV", gloss: "always", role: "adverb", ws: "" }),
  punct(".", " "),
  ar("العمل", { lemma: "عمل", pos: "NOUN", case: "nom", gender: "masc", number: "sg", state: "def", gloss: "work" }),
  ar("اليوم", { lemma: "يوم", pos: "NOUN", case: "nom", gender: "masc", number: "sg", state: "def", gloss: "today" }),
  ar("لا", { pos: "PART", gloss: "not" }),
  ar("ينتظر", { lemma: "انتظر", pos: "VERB", tense: "pres", mood: "indc", voice: "act", person: "3", number: "sg", form: "VIII", gloss: "to wait", role: "verb", root: NZL, level: "A2" }),
  punct("،", " "),
  ar("لأن", { pos: "ADP", gloss: "because", role: "particle", level: "B1" }),
  ar("اليوم", { lemma: "يوم", pos: "NOUN", case: "nom", gender: "masc", number: "sg", state: "def", gloss: "today" }),
  ar("عطلة", { pos: "NOUN", case: "nom", gender: "fem", number: "sg", state: "indef", gloss: "holiday", level: "A2", ws: "" }),
  punct(".", " "),
  ar("ثم", { pos: "ADV", gloss: "then", role: "adverb" }),
  ar("أشتري", { lemma: "اشترى", pos: "VERB", tense: "pres", mood: "indc", voice: "act", person: "1", number: "sg", form: "VIII", gloss: "to buy", role: "verb", reading: "أَشْتَرِي", root: SHR, level: "A2" }),
  ar("ماء", { pos: "NOUN", case: "acc", gender: "masc", number: "sg", state: "indef", gloss: "water" }),
  ar("في", { pos: "ADP", gloss: "in", role: "particle" }),
  ar("المحطة", { lemma: "محطة", pos: "NOUN", case: "gen", gender: "fem", number: "sg", state: "def", gloss: "station", level: "A2", ws: "" }),
  punct(".", " "),
  ar("المدينة", { lemma: "مدينة", pos: "NOUN", case: "nom", gender: "fem", number: "sg", state: "def", gloss: "city" }),
  ar("قريبة", { lemma: "قريب", pos: "ADJ", gender: "fem", number: "sg", gloss: "nearby", role: "adj" }),
  ar("الآن", { pos: "ADV", gloss: "now", role: "adverb", ws: "" }),
  punct("."),
];

export const DEMO_PASSAGES: Passage[] = [
  makePassage({
    id: "demo-ja-asa",
    language: "ja",
    level: "A1",
    topic: "a quiet morning at home",
    genre: "daily_life",
    title: "私の朝",
    tokens: JA_ASA,
    created_at: "2026-01-01T00:00:00Z",
    translation:
      "I am a student. Today is a day off. In the morning I drink water. This is bread. The bread is delicious. Mother is at home. Mother is well. This is tea. The tea is good. I read a book. The book is new. This is an apple. The apple is delicious. The house is clean.",
  }),
  makePassage({
    id: "demo-ja-ichiba",
    language: "ja",
    level: "A2",
    topic: "a trip to the market",
    genre: "daily_life",
    title: "母と市場",
    tokens: JA_ICHIBA,
    created_at: "2026-01-02T00:00:00Z",
    translation:
      "Today is Friday. I go to the market with my mother. The market is near the house. I got up early in the morning. I bought two apples. I also bought bread. There are many people at the market. Then we go home.",
  }),
  fromDemo(
    "demo-ja-pan",
    "ja",
    "In the morning I went to the bakery near the station. The person in the shop is always cheerful. I bought melon bread and coffee. I ate the bread in the park. The weather was good, and I felt good.",
    "2026-01-10T00:00:00Z",
  ),
  makePassage({
    id: "demo-ja-densha",
    language: "ja",
    level: "B1",
    topic: "reading on the train",
    genre: "daily_life",
    title: "電車で本を読む",
    tokens: JA_DENSHA,
    created_at: "2026-01-03T00:00:00Z",
    translation:
      "Right now I am reading a book on the train. The person next to me is looking at the window. When I arrive at the station, I will meet a friend. My friend works in Kyoto. If it rains, I will wait at the hotel. The book is new and very interesting. Work at the company is busy, but today is a day off.",
  }),
  makePassage({
    id: "demo-ru-anna",
    language: "ru",
    level: "A1",
    topic: "this is Anna",
    genre: "daily_life",
    title: "Это Анна",
    tokens: RU_ANNA,
    created_at: "2026-01-01T00:00:00Z",
    translation:
      "I am a student. This is a book. The book is new. Mom is here. This is water. The water is cold. This is tea. The tea is good. Anna is here. Anna is a student. The day is good.",
  }),
  fromDemo(
    "demo-ru-rynok",
    "ru",
    "Every morning I go to the market. There they sell fresh bread and cheese. I buy apples and say to the seller: “Good morning!” Then I go home and drink tea.",
    "2026-01-10T00:00:00Z",
  ),
  makePassage({
    id: "demo-ru-poezd",
    language: "ru",
    level: "A2",
    topic: "a train to the city",
    genre: "travel",
    title: "Поезд в город",
    tokens: RU_POEZD,
    created_at: "2026-01-02T00:00:00Z",
    translation:
      "Today I go to the city. The station is nearby. I buy a ticket. On the train I read a book and drink water. Yesterday I was at home. A friend waits for me at the station. The city is big.",
  }),
  makePassage({
    id: "demo-ru-kniga",
    language: "ru",
    level: "B1",
    topic: "reading on the train",
    genre: "daily_life",
    title: "Книга в поезде",
    tokens: RU_KNIGA,
    created_at: "2026-01-03T00:00:00Z",
    translation:
      "Right now I am on a train and reading a book. If a friend calls, I will get off at the station. Work is not waiting for me today, because it is a day off. When the train stops, I will buy water. The city is already close.",
  }),
  makePassage({
    id: "demo-it-casa",
    language: "it",
    level: "A1",
    topic: "a student at home",
    genre: "daily_life",
    title: "Anna a casa",
    tokens: IT_CASA,
    created_at: "2026-01-01T00:00:00Z",
    translation:
      "Anna is a student. Anna is here. This is a room. The room is new. This is a book. The book is new. This is tea. The tea is good. Mom is here. I am a student.",
  }),
  fromDemo(
    "demo-it-mercato",
    "it",
    "Every morning Anna goes to the market. There they sell fresh bread and cheese. Anna buys apples and says to the seller: “Good morning!” Then she goes home and drinks tea.",
    "2026-01-10T00:00:00Z",
  ),
  makePassage({
    id: "demo-it-treno",
    language: "it",
    level: "A2",
    topic: "a train to the city",
    genre: "travel",
    title: "Un treno in città",
    tokens: IT_TRENO,
    created_at: "2026-01-02T00:00:00Z",
    translation:
      "Today I go to the city. The station is nearby. I buy a ticket. On the train I read a book and drink water. Yesterday I was at home. A friend waits at the station. The city is large.",
  }),
  makePassage({
    id: "demo-it-libro",
    language: "it",
    level: "B1",
    topic: "reading on the train",
    genre: "daily_life",
    title: "Un libro sul treno",
    tokens: IT_LIBRO,
    created_at: "2026-01-03T00:00:00Z",
    translation:
      "Right now I am on a train and reading a book. When I was a child, I always read on the train. Work is not waiting today, because it is Sunday. Then I buy water at the station. The city is already close.",
  }),
  makePassage({
    id: "demo-ar-bait",
    language: "ar",
    level: "A1",
    topic: "a student at home",
    genre: "daily_life",
    title: "أحمد في البيت",
    tokens: AR_BAIT,
    created_at: "2026-01-01T00:00:00Z",
    translation:
      "This is Ahmad. Ahmad is a student. Ahmad is here. This is a house. The house is big. This is a room. The room is new. This is a book. The book is new. Mom is here. The tea is good. The water is cold. I am a student.",
  }),
  fromDemo(
    "demo-ar-suq",
    "ar",
    "Every morning I go to the market. There I buy bread and water. Ahmad buys apples and says to the seller: “Good morning!” Then I read my book.",
    "2026-01-10T00:00:00Z",
  ),
  makePassage({
    id: "demo-ar-qitar",
    language: "ar",
    level: "A2",
    topic: "a train to the city",
    genre: "travel",
    title: "قطار إلى المدينة",
    tokens: AR_QITAR,
    created_at: "2026-01-02T00:00:00Z",
    translation:
      "Today I go to the city. The station is nearby. I buy a ticket. On the train I read a book and drink water. Yesterday I was at home. A friend waits at the station. The city is large.",
  }),
  makePassage({
    id: "demo-ar-kitab",
    language: "ar",
    level: "B1",
    topic: "reading on the train",
    genre: "daily_life",
    title: "كتاب في القطار",
    tokens: AR_KITAB,
    created_at: "2026-01-03T00:00:00Z",
    translation:
      "Right now I am on the train and reading a book. When I was little I always read on the train. Work is not waiting today, because it is a holiday. Then I buy water at the station. The city is already close.",
  }),
];

function glossWord(language: LangCode, text: string, gloss: string, pos: string): Token {
  return {
    text,
    ws: language === "ja" ? "" : " ",
    is_word: true,
    lemma: text,
    morph: {
      lemma: text,
      pos,
      case: null,
      gender: null,
      number: null,
      tense: null,
      aspect: null,
      mood: null,
      reading: null,
      form: null,
    },
    gloss,
    level: "A2",
  };
}

function glossStop(text: string): Token {
  return { text, ws: /[。！？]/.test(text) ? "" : " ", is_word: false, lemma: null, morph: null, gloss: null, level: null };
}

const NEWS_QUESTIONS = [
  {
    id: "q1",
    prompt: "The morning train was ___.",
    choices: ["late", "cancelled for a year", "flying"],
    answer_index: 0,
  },
  {
    id: "q2",
    prompt: "Which of these happens in the passage?",
    choices: ["People waited at the station.", "Someone flew to the moon.", "The text is a recipe."],
    answer_index: 0,
  },
];

DEMO_PASSAGES.push(
  makePassage({
    id: "demo-ja-news",
    language: "ja",
    level: "A2",
    topic: "a late morning train",
    genre: "news",
    title: "朝の電車",
    tokens: [
      glossWord("ja", "けさ", "this morning", "noun"),
      glossStop("、"),
      glossWord("ja", "市内", "in the city", "noun"),
      glossWord("ja", "の", "of", "particle"),
      glossWord("ja", "電車", "train", "noun"),
      glossWord("ja", "が", "subject", "particle"),
      glossWord("ja", "遅れました", "was late", "verb"),
      glossStop("。"),
      glossWord("ja", "駅", "station", "noun"),
      glossWord("ja", "で", "at", "particle"),
      glossWord("ja", "多くの", "many", "adj"),
      glossWord("ja", "人", "people", "noun"),
      glossWord("ja", "が", "subject", "particle"),
      glossWord("ja", "待ちました", "waited", "verb"),
      glossStop("。"),
    ],
    translation: "This morning the city train was late. Many people waited at the station.",
    created_at: "2026-09-22T08:00:00Z",
    comprehension: NEWS_QUESTIONS,
    source_name: "Demo wire",
    source_date: "2026-09-22",
  }),
  makePassage({
    id: "demo-ru-news",
    language: "ru",
    level: "A2",
    topic: "a late morning train",
    genre: "news",
    title: "Утренний поезд",
    tokens: [
      glossWord("ru", "Утром", "in the morning", "ADVB"),
      glossWord("ru", "городской", "city", "ADJF"),
      glossWord("ru", "поезд", "train", "NOUN"),
      glossWord("ru", "опоздал", "was late", "VERB"),
      glossStop("."),
      glossWord("ru", "На", "at", "PREP"),
      glossWord("ru", "вокзале", "station", "NOUN"),
      glossWord("ru", "люди", "people", "NOUN"),
      glossWord("ru", "ждали", "waited", "VERB"),
      glossStop("."),
    ],
    translation: "In the morning the city train was late. People waited at the station.",
    created_at: "2026-09-22T08:00:00Z",
    comprehension: NEWS_QUESTIONS,
    source_name: "Demo wire",
    source_date: "2026-09-22",
  }),
  makePassage({
    id: "demo-it-news",
    language: "it",
    level: "A2",
    topic: "a late morning train",
    genre: "news",
    title: "Il treno del mattino",
    tokens: [
      glossWord("it", "Stamattina", "this morning", "ADV"),
      glossWord("it", "il", "the", "DET"),
      glossWord("it", "treno", "train", "NOUN"),
      glossWord("it", "della", "of the", "PREP"),
      glossWord("it", "città", "city", "NOUN"),
      glossWord("it", "era", "was", "VERB"),
      glossWord("it", "in", "in", "PREP"),
      glossWord("it", "ritardo", "delay", "NOUN"),
      glossStop("."),
      glossWord("it", "Alla", "at the", "PREP"),
      glossWord("it", "stazione", "station", "NOUN"),
      glossWord("it", "molte", "many", "ADJ"),
      glossWord("it", "persone", "people", "NOUN"),
      glossWord("it", "hanno", "have", "VERB"),
      glossWord("it", "aspettato", "waited", "VERB"),
      glossStop("."),
    ],
    translation: "This morning the city train was late. Many people waited at the station.",
    created_at: "2026-09-22T08:00:00Z",
    comprehension: NEWS_QUESTIONS,
    source_name: "Demo wire",
    source_date: "2026-09-22",
  }),
  makePassage({
    id: "demo-ar-news",
    language: "ar",
    level: "A2",
    topic: "a late morning train",
    genre: "news",
    title: "قطار الصباح",
    tokens: [
      glossWord("ar", "في", "in", "ADP"),
      glossWord("ar", "الصباح", "the morning", "NOUN"),
      glossWord("ar", "تأخر", "was late", "VERB"),
      glossWord("ar", "قطار", "train", "NOUN"),
      glossWord("ar", "المدينة", "the city", "NOUN"),
      glossStop("."),
      glossWord("ar", "في", "at", "ADP"),
      glossWord("ar", "المحطة", "the station", "NOUN"),
      glossWord("ar", "انتظر", "waited", "VERB"),
      glossWord("ar", "كثير", "many", "ADJ"),
      glossWord("ar", "من", "of", "ADP"),
      glossWord("ar", "الناس", "people", "NOUN"),
      glossStop("."),
    ],
    translation: "In the morning the city train was late. Many people waited at the station.",
    created_at: "2026-09-22T08:00:00Z",
    comprehension: NEWS_QUESTIONS,
    source_name: "Demo wire",
    source_date: "2026-09-22",
  }),
);

const BY_ID = new Map(DEMO_PASSAGES.map((p) => [p.id, p]));

export function getDemoPassage(id: string): Passage | undefined {
  return BY_ID.get(id);
}

export function listDemoPassages(language: LangCode): Passage[] {
  return DEMO_PASSAGES.filter((p) => p.language === language);
}

export function demoPassageIds(): string[] {
  return DEMO_PASSAGES.map((p) => p.id);
}
